# Preliminaries (Always run)

In [ ]:
from google.colab import drive

drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [ ]:
!pip install supervision

Requirement already satisfied: supervision in /usr/local/lib/python3.11/dist-packages (0.25.1)
Requirement already satisfied: contourpy>=1.0.7 in /usr/local/lib/python3.11/dist-packages (from supervision) (1.3.2)
Requirement already satisfied: defusedxml<0.8.0,>=0.7.1 in /usr/local/lib/python3.11/dist-packages (from supervision) (0.7.1)
Requirement already satisfied: matplotlib>=3.6.0 in /usr/local/lib/python3.11/dist-packages (from supervision) (3.10.0)
Requirement already satisfied: numpy>=1.21.2 in /usr/local/lib/python3.11/dist-packages (from supervision) (2.0.2)
Requirement already satisfied: opencv-python>=4.5.5.64 in /usr/local/lib/python3.11/dist-packages (from supervision) (4.11.0.86)
Requirement already satisfied: pillow>=9.4 in /usr/local/lib/python3.11/dist-packages (from supervision) (11.1.0)
Requirement already satisfied: pyyaml>=5.3 in /usr/local/lib/python3.11/dist-packages (from supervision) (6.0.2)
Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.11/dist-packages (from supervision) (2.32.3)
Requirement already satisfied: scipy<2.0.0,>=1.10.0 in /usr/local/lib/python3.11/dist-packages (from supervision) (1.14.1)
Requirement already satisfied: tqdm>=4.62.3 in /usr/local/lib/python3.11/dist-packages (from supervision) (4.67.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.6.0->supervision) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.6.0->supervision) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.6.0->supervision) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.6.0->supervision) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.6.0->supervision) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.6.0->supervision) (2.8.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.26.0->supervision) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.26.0->supervision) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.26.0->supervision) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.26.0->supervision) (2025.1.31)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib>=3.6.0->supervision) (1.17.0)

In [ ]:
import json
import numpy as np
import os
import pandas as pd
import math
import random
import cv2
import torch
import supervision as sv
from PIL import Image
import re

In [ ]:
vitpose_path = "/content/drive/Shareddrives/shoplifting-dataset/vitpose_results_70"
yolo_path = "/content/drive/Shareddrives/shoplifting-dataset/pose_estimation_results_70/YOLOv70"
input_path = "/content/drive/Shareddrives/thesis/dataset/split/Shoplifting"
output_path = "/content/drive/Shareddrives/thesis/dataset"

# Processing Features

In [ ]:
# WIP
# def get_confidences(row):
#   confidences = []
#   for i in range(MAX_DETECTIONS):
#     if row[f"Person_{i}_keypoints"]:
#       for keypoint in row[f"Person_{i}_keypoints"]:
#           confidences.append(keypoint["score"])
#   return np.array(confidences)

# confidence_series = clips_data.map(get_confidences)
# maxes = confidence_series.map(max)
# mins = confidence_series.map(min)
# num_keypoints = sum(confidences_series.map(sum))
# print(min(mins), max(mins))
# print(min(maxes), max(maxes))
# proportions = {}
# for i in range(5, 100, 5):
#   threshold = i/100
#   num_below = sum(confidence_series.map(lambda confs: sum(confs < threshold)))
#   print(threshold, num_clips, num_below/num_keypoints)

In [ ]:
# Features

#Functions currently assume complete required keypoints
joint_indices_all = {'Nose': 0, 'L_Eye': 1, 'R_Eye': 2, 'L_Ear': 3, 'R_Ear': 4, 'L_Shoulder': 5, 'R_Shoulder': 6, 'L_Elbow': 7, 'R_Elbow': 8, 'L_Wrist': 9, 'R_Wrist': 10, 'L_Hip': 11, 'R_Hip': 12, 'L_Knee': 13, 'R_Knee': 14, 'L_Ankle': 15, 'R_Ankle': 16}
# joint_indices_required = {'Neck': 0, 'L_Shoulder': 1, 'R_Shoulder': 2, 'L_Elbow': 3, 'R_Elbow': 4, 'L_Wrist': 5, 'R_Wrist': 6, 'L_Hip': 7, 'R_Hip': 8}
joint_indices_required = {'Neck': 0, 'L_Eye': 1, 'R_Eye': 2, 'L_Shoulder': 3, 'R_Shoulder': 4, 'L_Elbow': 5, 'R_Elbow': 6, 'L_Wrist': 7, 'R_Wrist': 8, 'L_Hip': 9, 'R_Hip': 10}
# Relevant pairs
pairs = [('Neck', 'R_Shoulder'), ('Neck', 'L_Shoulder'), ('R_Shoulder', 'R_Elbow'), ('L_Shoulder', 'L_Elbow'), ('R_Elbow', 'R_Wrist'), ('L_Elbow', 'L_Wrist'), ('R_Wrist', 'R_Hip'), ('L_Wrist', 'L_Hip')]


def add_neck(keypoints):
    l, r = joint_indices_all["L_Shoulder"], joint_indices_all["R_Shoulder"]
    if keypoints[l]["x"] == keypoints[l]["y"] == 0:
      neck_x = keypoints[r]["x"]
      neck_y = keypoints[r]["y"]
    elif keypoints[r]["x"] == keypoints[r]["y"] == 0:
      neck_x = keypoints[l]["x"]
      neck_y = keypoints[l]["y"]
    else:
      neck_x = (keypoints[l]["x"] + keypoints[r]["x"]) / 2
      neck_y = (keypoints[l]["y"] + keypoints[r]["y"]) / 2
    avg_score = (keypoints[l]["score"] + keypoints[r]["score"]) / 2
    return [{"name": "Neck", "x": neck_x, "y": neck_y, "score": avg_score}] + keypoints

def get_required(keypoints):
  '''requires keypoints with neck added'''
  required = []
  for joint in joint_indices_required:
      #gets new index now that neck is included
      ind = joint_indices_all.get(joint, -1) + 1
      required.append(keypoints[ind].copy())
  return required

def normalize_keypoints(keypoints, avg_height):
  normalized = []
  for keypoint in keypoints:
    normalized.append(keypoint.copy())
    normalized[-1]["x"] /= avg_height
    normalized[-1]["y"] /= avg_height
  return normalized

def scale_keypoints(keypoints):
  neck = keypoints[0]
  neck_x = neck["x"]
  neck_y = neck["y"]
  scaled = []
  for keypoint in keypoints:
    scaled.append(keypoint.copy())
    scaled[-1]["x"] -= neck_x
    scaled[-1]["y"] -= neck_y
  return scaled

def get_skeleton(keypoints):
  skeleton = []
  for keypoint in keypoints:
    skeleton.append(keypoint["x"])
    skeleton.append(keypoint["y"])
  return skeleton

def has_required(keypoints):
  '''requires complete unscaled keypoints with neck added'''
  for j in joint_indices_required:
    ind = joint_indices_all.get(j, -1) + 1
    if keypoints[ind]["x"] == keypoints[ind]["y"] == 0:
      return False
  return True

def has_neck(keypoints):
  return keypoints[0]["x"] != 0 or keypoints[0]["y"] != 0

#NOTE: following functions assumes only required keypoints are given

def get_angles(keypoints):
  angles = []
  for joint_i, joint_j in pairs:
    i = joint_indices_required[joint_i]
    j = joint_indices_required[joint_j]
    # if keypoints[i]["x"] == keypoints[i]["y"] == 0 or keypoints[j]["x"] == keypoints[j]["y"] == 0:
    #   angles.append(0)
    # else:
    angles.append(math.atan2(keypoints[i]["y"] - keypoints[j]["y"], keypoints[i]["x"] - keypoints[j]["x"]))
  return angles

def get_lengths(keypoints):
  lengths = []
  for joint_i, joint_j in pairs:
    i = joint_indices_required[joint_i]
    j = joint_indices_required[joint_j]
    # if keypoints[i]["x"] == keypoints[i]["y"] == 0 or keypoints[j]["x"] == keypoints[j]["y"] == 0:
    #   lengths.append(0)
    # else:
    lengths.append(math.sqrt((keypoints[j]["y"] - keypoints[i]["y"]) ** 2 + (keypoints[j]["x"] - keypoints[i]["x"]) ** 2))
  return lengths

def get_motion(keypoints_prev, keypoints_cur):
  motion = []
  for keypoint_prev, keypoint_cur in zip(keypoints_prev, keypoints_cur):
    motion.extend((keypoint_cur["y"] - keypoint_prev["y"], keypoint_cur["x"] - keypoint_prev["x"]))
  return motion

def get_height(keypoints):
  neck = keypoints[joint_indices_required["Neck"]]
  left_hip = keypoints[joint_indices_required["L_Hip"]]
  right_hip = keypoints[joint_indices_required["R_Hip"]]
  x0, y0 = neck["x"], neck["y"]
  x11, y11 = left_hip["x"], left_hip["y"]
  x12, y12 = right_hip["x"], right_hip["y"]
  if not y11 and not y12:
    return 1.0
  if not y11:
    x1, y1 = x12, y12
  elif not y12:
    x1, y1 = x11, y11
  else:
    x1, y1 = (x11 + x12) / 2, (y11 + y12) / 2
  height = math.sqrt((x0 - x1) ** 2 + (y0 - y1) ** 2)
  return height

def get_feature_vector(person_file, good_frames, n_frames=120, padding=None):
  '''padding is one of None, "after", "between"'''
  #TODO: use fpc, work with missing frames
  person = json.load(person_file)
  add_missing(person)
  good_frames = set(good_frames)
  frames = []
  heights = []
  for i in range(n_frames):
    if str(i) not in good_frames:
      frames.append(None)
      continue
    frame = f"frame_{i}"
    #keypoints should have neck
    keypoints = person[frame][0]["keypoints"]
    frames.append(get_required(keypoints))
    heights.append(get_height(frames[-1]))
  avg_height = sum(heights) / len(heights)

  skeletons = []
  angles = []
  motion = []
  lengths = []

  i = 0
  while frames[i] == None:
    if padding == "between":
      skeletons += [0] * 2 * len(joint_indices_required)
      angles += [0] * len(pairs)
      lengths += [0] * (len(pairs))
      motion += [0] * 2 * len(joint_indices_required)
    i += 1

  frame = frames[i]
  normalized_frame = normalize_keypoints(scale_keypoints(frame), avg_height)
  skeletons.extend(get_skeleton(normalized_frame))
  lengths.extend(get_lengths(frame))
  angles.extend(get_angles(frame))
  frame_prev = frame
  i += 1
  while i < n_frames:
    frame = frames[i]
    if frames[i] == None:
      if padding == "between":
        skeletons += [0] * 2 * len(joint_indices_required)
        angles += [0] * len(pairs)
        lengths += [0] * (len(pairs))
        motion += [0] * 2 * len(joint_indices_required)
      i += 1
      continue
    normalized_frame = normalize_keypoints(scale_keypoints(frame), avg_height)
    skeletons.extend(get_skeleton(normalized_frame))
    lengths.extend(get_lengths(frame))
    angles.extend(get_angles(frame))
    motion.extend(get_motion(frame_prev, frame))
    frame_prev = frame
    i += 1

  #pad after
  if padding == "after":
    skeletons += [0] * 2 * len(joint_indices_required) * (n_frames - len(good_frames))
    angles += [0] * len(pairs) * (n_frames - len(good_frames))
    lengths += [0] * (len(pairs)) * (n_frames - len(good_frames))
    motion += [0] * 2 * len(joint_indices_required) * (n_frames - len(good_frames))
  return skeletons + motion + angles + lengths

In [ ]:
def add_missing(person):
  prev = None
  for frame in person:
    if prev == None:
      prev = person[frame][0]["keypoints"]
      continue

    cur = person[frame][0]["keypoints"]
    for i in range(len(cur)):
      keypoint = cur[i]
      if keypoint["x"] == keypoint["y"] == 0:
        keypoint["x"] = prev[i]["x"]
        keypoint["y"] = prev[i]["y"]
        keypoint["score"] = prev[i]["score"]
    prev = cur

In [ ]:
# #updated function
# def add_missing(person):
#   prev_frame = None
#   MIN_FRAMES = 5
#   for frame in person):
#     cur = person[frame][0]["keypoints"]
#     neck = cur[0]
#     if neck["x"] == neck["y"] == 0: #no neck
#       continue

#     if prev_frame == None:
#       prev_frame = frame
#       continue

#     #only update current frame if previous frame is recent
#     dist = int(frame[frame.find('_') + 1:]) - int(prev_frame[prev_frame.find('_') + 1:])
#     if dist <= MIN_FRAMES:
#       prev_frame = frame
#       continue

#     #prev contains the coordinates w.r.t. neck
#     prev = scale_keypoints(person[prev_frame][0]["keypoints"])
#     for i in range(len(cur)):
#       keypoint = cur[i]
#       if keypoint["x"] == keypoint["y"] == 0:
#         keypoint["x"] = neck["x"] + prev[i]["x"]
#         keypoint["y"] = neck["y"] + prev[i]["y"]
#         keypoint["score"] = prev[i]["score"]

#     prev_frame = frame

In [ ]:
#test code
complete_keypoints = [
        {
          "name": "Nose",
          "x": 0.21296,
          "y": 0.197395,
          "score": 0.957988
        },
        {
          "name": "L_Eye",
          "x": 0.21935,
          "y": 0.188178,
          "score": 0.932745
        },
        {
          "name": "R_Eye",
          "x": 0.205316,
          "y": 0.188616,
          "score": 0.927804
        },
        {
          "name": "L_Ear",
          "x": 0.226949,
          "y": 0.19677,
          "score": 0.53724
        },
        {
          "name": "R_Ear",
          "x": 0.192757,
          "y": 0.197992,
          "score": 0.654674
        },
        {
          "name": "L_Shoulder",
          "x": 0.235987,
          "y": 0.257017,
          "score": 0.989575
        },
        {
          "name": "R_Shoulder",
          "x": 0.182495,
          "y": 0.259874,
          "score": 0.945271
        },
        {
          "name": "L_Elbow",
          "x": 0.251025,
          "y": 0.336221,
          "score": 0.924226
        },
        {
          "name": "R_Elbow",
          "x": 1.0,
          "y": 1.0,
          "score": 0.47833
        },
        {
          "name": "L_Wrist",
          "x": 0.249079,
          "y": 0.414618,
          "score": 0.84689
        },
        {
          "name": "R_Wrist",
          "x": 1.0,
          "y": 1.0,
          "score": 0.437973
        },
        {
          "name": "L_Hip",
          "x": 0.224901,
          "y": 0.40113,
          "score": 0.993834
        },
        {
          "name": "R_Hip",
          "x": 0.189735,
          "y": 0.403957,
          "score": 0.984873
        },
        {
          "name": "L_Knee",
          "x": 0.231089,
          "y": 0.507317,
          "score": 0.99508
        },
        {
          "name": "R_Knee",
          "x": 0.195687,
          "y": 0.516484,
          "score": 0.985501
        },
        {
          "name": "L_Ankle",
          "x": 0.234915,
          "y": 0.600612,
          "score": 0.987405
        },
        {
          "name": "R_Ankle",
          "x": 0.206645,
          "y": 0.612397,
          "score": 0.970394
        }
      ]

missing_keypoints = [
  {
    "name": "Nose",
    "x": 0.21296,
    "y": 0.197395,
    "score": 0.957988
  },
  {
    "name": "L_Eye",
    "x": 0.21935,
    "y": 0.188178,
    "score": 0.932745
  },
  {
    "name": "R_Eye",
    "x": 0.205316,
    "y": 0.188616,
    "score": 0.927804
  },
  {
    "name": "L_Ear",
    "x": 0.226949,
    "y": 0.19677,
    "score": 0.53724
  },
  {
    "name": "R_Ear",
    "x": 0.192757,
    "y": 0.197992,
    "score": 0.654674
  },
  {
    "name": "L_Shoulder",
    "x": 0.235987,
    "y": 0.257017,
    "score": 0.989575
  },
  {
    "name": "R_Shoulder",
    "x": 0.0,
    "y": 0.0,
    "score": 0.945271
  },
  {
    "name": "L_Elbow",
    "x": 0.251025,
    "y": 0.336221,
    "score": 0.924226
  },
  {
    "name": "R_Elbow",
    "x": 1.0,
    "y": 1.0,
    "score": 0.47833
  },
  {
    "name": "L_Wrist",
    "x": 0.249079,
    "y": 0.414618,
    "score": 0.84689
  },
  {
    "name": "R_Wrist",
    "x": 1.0,
    "y": 1.0,
    "score": 0.437973
  },
  {
    "name": "L_Hip",
    "x": 0.224901,
    "y": 0.40113,
    "score": 0.993834
  },
  {
    "name": "R_Hip",
    "x": 0.189735,
    "y": 0.403957,
    "score": 0.984873
  },
  {
    "name": "L_Knee",
    "x": 0.231089,
    "y": 0.507317,
    "score": 0.99508
  },
  {
    "name": "R_Knee",
    "x": 0.195687,
    "y": 0.516484,
    "score": 0.985501
  },
  {
    "name": "L_Ankle",
    "x": 0.234915,
    "y": 0.600612,
    "score": 0.987405
  },
  {
    "name": "R_Ankle",
    "x": 0.206645,
    "y": 0.612397,
    "score": 0.970394
  }
]

neck_x = (complete_keypoints[5]["x"] + complete_keypoints[6]["x"]) / 2
neck_y = (complete_keypoints[5]["y"] + complete_keypoints[6]["y"]) / 2
keypoints = add_neck(complete_keypoints)
assert keypoints[0]["x"] == neck_x
assert keypoints[0]["y"] == neck_y
scaled_keypoints = scale_keypoints(keypoints)
for keypoint, scaled in zip(keypoints, scaled_keypoints):
  assert keypoint["x"] - neck_x == scaled["x"]
  assert keypoint["y"] - neck_y == scaled["y"]
clip = {"frame_0": [{"keypoints": add_neck(complete_keypoints)}], "frame_1": [{"keypoints": add_neck(missing_keypoints)}]}
assert not has_required(clip["frame_1"][0]["keypoints"])
add_missing(clip)
assert has_required(clip["frame_1"][0]["keypoints"])
assert clip["frame_1"][0]["keypoints"][2]["x"] == clip["frame_0"][0]["keypoints"][2]["x"]
assert clip["frame_1"][0]["keypoints"][2]["y"] == clip["frame_0"][0]["keypoints"][2]["y"]

In [ ]:
#make uniformly named keypoint json files with neck keypoint added
clips = pd.read_csv(f"{output_path}/shoplifting_ids.csv")
clips["List of Shoplifter ID"] = clips["List of Shoplifter ID"].fillna("[]")
for i in range(len(clips)):
  row = clips.iloc[i]
  clip = row["Clip"]
  print(clip)
  parent = row["Parent Video"]
  label = row["Label"]
  if label == 1:
    ids = json.loads(row["List of Shoplifter ID"])
  elif label == 0:
    ids = json.loads(row["List of Unique ID"])
  else:
    continue
  for id in ids:
    if os.path.exists(f"{yolo_path}/{parent}/{clip}/new_person_{id}.json"):
      with open(f"{yolo_path}/{parent}/{clip}/new_person_{id}.json") as f:
        person = json.load(f)
    else:
      with open(f"{yolo_path}/{parent}/{clip}/person_{id}.json") as f:
        person = json.load(f)

    #add neck to keypoints
    for frame in person:
      person[frame][0]["keypoints"] = add_neck(person[frame][0]["keypoints"])
    os.makedirs(f"{yolo_path}/{parent}/{clip}/persons/person_{id}", exist_ok=True)
    with open(f"{yolo_path}/{parent}/{clip}/persons/person_{id}/keypoints_0.json", 'w') as f:
      json.dump(person, f)

Shoplifting038_x264_24
Shoplifting029_x264_18
Shoplifting001_x264_10
Shoplifting001_x264_11
Shoplifting001_x264_12
Shoplifting001_x264_13
Shoplifting001_x264_14
Shoplifting001_x264_15
Shoplifting001_x264_16
Shoplifting003_x264_56
Shoplifting003_x264_57
Shoplifting003_x264_58
Shoplifting003_x264_59
Shoplifting003_x264_60
Shoplifting003_x264_61
Shoplifting003_x264_62
Shoplifting003_x264_63
Shoplifting004_x264_38
Shoplifting004_x264_39
Shoplifting004_x264_40
Shoplifting004_x264_41
Shoplifting005_x264_6
Shoplifting005_x264_7
Shoplifting006_x264_10
Shoplifting006_x264_11
Shoplifting006_x264_12
Shoplifting006_x264_13
Shoplifting006_x264_14
Shoplifting007_x264_4
Shoplifting007_x264_5
Shoplifting007_x264_6
Shoplifting007_x264_7
Shoplifting007_x264_8
Shoplifting008_x264_42
Shoplifting008_x264_43
Shoplifting008_x264_44
Shoplifting008_x264_45
Shoplifting009_x264_36
Shoplifting009_x264_37
Shoplifting009_x264_38
Shoplifting009_x264_39
Shoplifting009_x264_40
Shoplifting009_x264_41
Shoplifting009_x264_42
Shoplifting010_x264_5
Shoplifting010_x264_6
Shoplifting010_x264_7
Shoplifting010_x264_8
Shoplifting012_x264_66
Shoplifting012_x264_67
Shoplifting012_x264_68
Shoplifting012_x264_88
Shoplifting012_x264_89
Shoplifting012_x264_90
Shoplifting012_x264_91
Shoplifting012_x264_92
Shoplifting013_x264_1
Shoplifting013_x264_2
Shoplifting013_x264_3
Shoplifting013_x264_4
Shoplifting013_x264_5
Shoplifting013_x264_6
Shoplifting013_x264_7
Shoplifting013_x264_8
Shoplifting013_x264_9
Shoplifting013_x264_10
Shoplifting013_x264_11
Shoplifting013_x264_12
Shoplifting013_x264_13
Shoplifting013_x264_14
Shoplifting013_x264_15
Shoplifting013_x264_16
Shoplifting014_x264_178
Shoplifting014_x264_179
Shoplifting014_x264_180
Shoplifting014_x264_280
Shoplifting014_x264_281
Shoplifting014_x264_282
Shoplifting014_x264_283
Shoplifting014_x264_284
Shoplifting014_x264_285
Shoplifting014_x264_414
Shoplifting014_x264_415
Shoplifting014_x264_416
Shoplifting014_x264_419
Shoplifting014_x264_420
Shoplifting014_x264_421
Shoplifting014_x264_422
Shoplifting014_x264_450
Shoplifting014_x264_451
Shoplifting014_x264_452
Shoplifting014_x264_453
Shoplifting014_x264_454
Shoplifting014_x264_455
Shoplifting014_x264_456
Shoplifting015_x264_16
Shoplifting015_x264_17
Shoplifting016_x264_4
Shoplifting016_x264_5
Shoplifting016_x264_6
Shoplifting017_x264_2
Shoplifting017_x264_3
Shoplifting018_x264_3
Shoplifting018_x264_4
Shoplifting018_x264_5
Shoplifting018_x264_6
Shoplifting018_x264_7
Shoplifting018_x264_8
Shoplifting018_x264_9
Shoplifting018_x264_10
Shoplifting018_x264_11
Shoplifting018_x264_12
Shoplifting019_x264_1
Shoplifting019_x264_2
Shoplifting019_x264_3
Shoplifting020_x264_18
Shoplifting020_x264_19
Shoplifting020_x264_20
Shoplifting021_x264_17
Shoplifting021_x264_18
Shoplifting022_x264_2
Shoplifting022_x264_3
Shoplifting022_x264_4
Shoplifting022_x264_5
Shoplifting022_x264_6
Shoplifting022_x264_7
Shoplifting022_x264_8
Shoplifting022_x264_9
Shoplifting022_x264_10
Shoplifting022_x264_11
Shoplifting022_x264_12
Shoplifting022_x264_13
Shoplifting022_x264_14
Shoplifting022_x264_15
Shoplifting022_x264_16
Shoplifting024_x264_6
Shoplifting024_x264_7
Shoplifting024_x264_8
Shoplifting025_x264_3
Shoplifting025_x264_4
Shoplifting025_x264_5
Shoplifting025_x264_6
Shoplifting026_x264_1
Shoplifting026_x264_2
Shoplifting026_x264_3
Shoplifting026_x264_4
Shoplifting026_x264_5
Shoplifting026_x264_6
Shoplifting026_x264_7
Shoplifting026_x264_8
Shoplifting026_x264_9
Shoplifting026_x264_10
Shoplifting027_x264_8
Shoplifting027_x264_9
Shoplifting028_x264_4
Shoplifting028_x264_5
Shoplifting028_x264_6
Shoplifting028_x264_7
Shoplifting028_x264_8
Shoplifting029_x264_9
Shoplifting029_x264_10
Shoplifting029_x264_11
Shoplifting029_x264_12
Shoplifting030_x264_135
Shoplifting030_x264_136
Shoplifting030_x264_137
Shoplifting030_x264_138
Shoplifting030_x264_139
Shoplifting030_x264_140
Shoplifting030_x264_141
Shoplifting031_x264_1
Shoplifting031_x264_2
Shoplifting031_x264_3
Shoplifting032_x264_7
Shoplifting032_x264_8
Shoplifting032_x264_9
Shoplifting033_x264_5
Shoplifting033_x264_6
Shoplifting034_x264_38
Shoplifting034_x264_39
Shoplifting034_x264_42
Shoplifting034_x264_43
Shoplifting034_x264_46
Shoplifting034_x264_47
Shoplifting034_x264_60
Shoplifting034_x264_61
Shoplifting034_x264_67
Shoplifting034_x264_68
Shoplifting034_x264_69
Shoplifting036_x264_25
Shoplifting036_x264_26
Shoplifting036_x264_27
Shoplifting036_x264_28
Shoplifting037_x264_8
Shoplifting037_x264_9
Shoplifting038_x264_12
Shoplifting038_x264_13
Shoplifting038_x264_20
Shoplifting038_x264_21
Shoplifting039_x264_17
Shoplifting039_x264_18
Shoplifting040_x264_15
Shoplifting040_x264_16
Shoplifting040_x264_37
Shoplifting040_x264_38
Shoplifting040_x264_39
Shoplifting040_x264_70
Shoplifting040_x264_71
Shoplifting040_x264_84
Shoplifting040_x264_85
Shoplifting040_x264_86
Shoplifting040_x264_108
Shoplifting040_x264_109
Shoplifting041_x264_17
Shoplifting041_x264_18
Shoplifting041_x264_56
Shoplifting041_x264_57
Shoplifting041_x264_58
Shoplifting041_x264_59
Shoplifting041_x264_60
Shoplifting041_x264_76
Shoplifting041_x264_77
Shoplifting042_x264_15
Shoplifting042_x264_16
Shoplifting042_x264_17
Shoplifting042_x264_18
Shoplifting042_x264_19
Shoplifting042_x264_20
Shoplifting042_x264_21
Shoplifting042_x264_22
Shoplifting042_x264_23
Shoplifting042_x264_24
Shoplifting043_x264_49
Shoplifting043_x264_50
Shoplifting043_x264_51
Shoplifting043_x264_52
Shoplifting043_x264_53
Shoplifting043_x264_54
Shoplifting043_x264_55
Shoplifting043_x264_56
Shoplifting043_x264_57
Shoplifting044_x264_86
Shoplifting044_x264_87
Shoplifting044_x264_88
Shoplifting044_x264_89
Shoplifting044_x264_90
Shoplifting044_x264_91
Shoplifting044_x264_92
Shoplifting044_x264_93
Shoplifting044_x264_94
Shoplifting044_x264_95
Shoplifting044_x264_96
Shoplifting045_x264_5
Shoplifting045_x264_6
Shoplifting045_x264_7
Shoplifting045_x264_8
Shoplifting045_x264_9
Shoplifting045_x264_10
Shoplifting045_x264_11
Shoplifting045_x264_12
Shoplifting047_x264_9
Shoplifting047_x264_10
Shoplifting047_x264_11
Shoplifting047_x264_13
Shoplifting047_x264_14
Shoplifting047_x264_15
Shoplifting047_x264_16
Shoplifting047_x264_17
Shoplifting047_x264_18
Shoplifting047_x264_19
Shoplifting048_x264_1
Shoplifting048_x264_2
Shoplifting048_x264_7
Shoplifting048_x264_8
Shoplifting048_x264_9
Shoplifting049_x264_8
Shoplifting049_x264_9
Shoplifting049_x264_10
Shoplifting049_x264_11
Shoplifting050_x264_0
Shoplifting050_x264_1
Shoplifting050_x264_2
Shoplifting050_x264_3
Shoplifting050_x264_4
Shoplifting050_x264_5
Shoplifting050_x264_6
Shoplifting050_x264_7
Shoplifting050_x264_8
Shoplifting050_x264_9
Shoplifting050_x264_10
Shoplifting050_x264_11
Shoplifting050_x264_12
Shoplifting050_x264_13
Shoplifting050_x264_14
Shoplifting050_x264_15
Shoplifting051_x264_38
Shoplifting051_x264_39
Shoplifting051_x264_40
Shoplifting051_x264_41
Shoplifting051_x264_42
Shoplifting051_x264_43
Shoplifting052_x264_6
Shoplifting052_x264_7
Shoplifting052_x264_8
Shoplifting052_x264_13
Shoplifting052_x264_14
Shoplifting052_x264_15
Shoplifting052_x264_22
Shoplifting052_x264_23
Shoplifting052_x264_32
Shoplifting052_x264_33
Shoplifting052_x264_39
Shoplifting052_x264_40
Shoplifting052_x264_41
Shoplifting053_x264_10
Shoplifting053_x264_11
Shoplifting053_x264_12
Shoplifting053_x264_13
Shoplifting054_x264_4
Shoplifting054_x264_5
Shoplifting054_x264_6
Shoplifting055_x264_17
Shoplifting055_x264_18
Shoplifting055_x264_19
Shoplifting055_x264_20
Shoplifting055_x264_21
Shoplifting055_x264_22
Shoplifting055_x264_23
Shoplifting055_x264_24
Shoplifting055_x264_25
nan
Shoplifting001_x264_0
Shoplifting001_x264_1
Shoplifting001_x264_2
Shoplifting001_x264_3
Shoplifting001_x264_4
Shoplifting001_x264_5
Shoplifting001_x264_6
Shoplifting001_x264_7
Shoplifting001_x264_8
Shoplifting001_x264_9
Shoplifting001_x264_17
Shoplifting001_x264_18
Shoplifting001_x264_19
Shoplifting001_x264_20
Shoplifting001_x264_21
Shoplifting001_x264_22
Shoplifting001_x264_23
Shoplifting001_x264_24
Shoplifting001_x264_25
Shoplifting001_x264_26
Shoplifting001_x264_27
Shoplifting001_x264_28
Shoplifting001_x264_29
Shoplifting001_x264_30
Shoplifting001_x264_31
Shoplifting001_x264_32
Shoplifting001_x264_33
Shoplifting001_x264_34
Shoplifting001_x264_35
Shoplifting001_x264_36
Shoplifting003_x264_0
Shoplifting003_x264_1
Shoplifting003_x264_2
Shoplifting003_x264_3
Shoplifting003_x264_4
Shoplifting003_x264_5
Shoplifting003_x264_6
Shoplifting003_x264_7
Shoplifting003_x264_8
Shoplifting003_x264_9
Shoplifting003_x264_10
Shoplifting003_x264_11
Shoplifting003_x264_12
Shoplifting003_x264_13
Shoplifting003_x264_14
Shoplifting003_x264_15
Shoplifting003_x264_16
Shoplifting003_x264_17
Shoplifting003_x264_18
Shoplifting003_x264_19
Shoplifting003_x264_20
Shoplifting003_x264_21
Shoplifting003_x264_22
Shoplifting003_x264_23
Shoplifting003_x264_24
Shoplifting003_x264_25
Shoplifting003_x264_26
Shoplifting003_x264_27
Shoplifting003_x264_28
Shoplifting003_x264_29
Shoplifting003_x264_30
Shoplifting003_x264_31
Shoplifting003_x264_32
Shoplifting003_x264_33
Shoplifting003_x264_34
Shoplifting003_x264_35
Shoplifting003_x264_36
Shoplifting003_x264_37
Shoplifting003_x264_38
Shoplifting003_x264_39
Shoplifting003_x264_40
Shoplifting003_x264_41
Shoplifting003_x264_42
Shoplifting003_x264_43
Shoplifting003_x264_44
Shoplifting003_x264_45
Shoplifting003_x264_46
Shoplifting003_x264_47
Shoplifting003_x264_48
Shoplifting003_x264_49
Shoplifting003_x264_50
Shoplifting003_x264_51
Shoplifting003_x264_52
Shoplifting003_x264_53
Shoplifting003_x264_54
Shoplifting003_x264_55
Shoplifting003_x264_64
Shoplifting003_x264_65
Shoplifting003_x264_66
Shoplifting003_x264_67
Shoplifting003_x264_68
Shoplifting003_x264_69
Shoplifting003_x264_70
Shoplifting003_x264_71
Shoplifting003_x264_72
Shoplifting003_x264_73
Shoplifting003_x264_74
Shoplifting003_x264_75
Shoplifting003_x264_76
Shoplifting003_x264_77
Shoplifting003_x264_78
Shoplifting003_x264_79
Shoplifting003_x264_80
Shoplifting003_x264_81
Shoplifting003_x264_82
Shoplifting003_x264_83
Shoplifting003_x264_84
Shoplifting003_x264_85
Shoplifting003_x264_86
Shoplifting003_x264_87
Shoplifting003_x264_88
Shoplifting003_x264_89
Shoplifting003_x264_90
Shoplifting004_x264_0
Shoplifting004_x264_1
Shoplifting004_x264_2
Shoplifting004_x264_3
Shoplifting004_x264_4
Shoplifting004_x264_5
Shoplifting004_x264_6
Shoplifting004_x264_7
Shoplifting004_x264_8
Shoplifting004_x264_9
Shoplifting004_x264_10
Shoplifting004_x264_11
Shoplifting004_x264_12
Shoplifting004_x264_13
Shoplifting004_x264_14
Shoplifting004_x264_15
Shoplifting004_x264_16
Shoplifting004_x264_17
Shoplifting004_x264_18
Shoplifting004_x264_19
Shoplifting004_x264_20
Shoplifting004_x264_21
Shoplifting004_x264_22
Shoplifting004_x264_23
Shoplifting004_x264_24
Shoplifting004_x264_25
Shoplifting004_x264_26
Shoplifting004_x264_27
Shoplifting004_x264_28
Shoplifting004_x264_29
Shoplifting004_x264_30
Shoplifting004_x264_31
Shoplifting004_x264_32
Shoplifting004_x264_33
Shoplifting004_x264_34
Shoplifting004_x264_35
Shoplifting004_x264_36
Shoplifting004_x264_37
Shoplifting004_x264_42
Shoplifting004_x264_43
Shoplifting004_x264_44
Shoplifting004_x264_45
Shoplifting004_x264_46
Shoplifting004_x264_47
Shoplifting004_x264_48
Shoplifting004_x264_49
Shoplifting004_x264_50
Shoplifting004_x264_51
Shoplifting004_x264_52
Shoplifting004_x264_53
Shoplifting004_x264_54
Shoplifting004_x264_55
Shoplifting005_x264_0
Shoplifting005_x264_1
Shoplifting005_x264_2
Shoplifting005_x264_3
Shoplifting005_x264_4
Shoplifting005_x264_5
Shoplifting005_x264_8
Shoplifting005_x264_9
Shoplifting005_x264_10
Shoplifting005_x264_11
Shoplifting005_x264_12
Shoplifting005_x264_13
Shoplifting005_x264_14
Shoplifting005_x264_15
Shoplifting005_x264_16
Shoplifting006_x264_0
Shoplifting006_x264_1
Shoplifting006_x264_2
Shoplifting006_x264_3
Shoplifting006_x264_4
Shoplifting006_x264_5
Shoplifting006_x264_6
Shoplifting006_x264_7
Shoplifting006_x264_8
Shoplifting006_x264_9
Shoplifting006_x264_15
Shoplifting006_x264_16
Shoplifting006_x264_17
Shoplifting006_x264_18
Shoplifting006_x264_19
Shoplifting006_x264_20
Shoplifting006_x264_21
Shoplifting006_x264_22
Shoplifting006_x264_23
Shoplifting006_x264_24
Shoplifting006_x264_25
Shoplifting006_x264_26
Shoplifting007_x264_0
Shoplifting007_x264_1
Shoplifting007_x264_2
Shoplifting007_x264_3
Shoplifting007_x264_9
Shoplifting007_x264_10
Shoplifting007_x264_11
Shoplifting007_x264_12
Shoplifting007_x264_13
Shoplifting007_x264_14
Shoplifting007_x264_15
Shoplifting007_x264_16
Shoplifting007_x264_17
Shoplifting007_x264_18
Shoplifting007_x264_19
Shoplifting007_x264_20
Shoplifting007_x264_21
Shoplifting007_x264_22
Shoplifting007_x264_23
Shoplifting007_x264_24
Shoplifting007_x264_25
Shoplifting007_x264_26
Shoplifting007_x264_27
Shoplifting007_x264_28
Shoplifting007_x264_29
Shoplifting007_x264_30
Shoplifting007_x264_31
Shoplifting007_x264_32
Shoplifting007_x264_33
Shoplifting007_x264_34
Shoplifting007_x264_35
Shoplifting007_x264_36
Shoplifting007_x264_37
Shoplifting007_x264_38
Shoplifting007_x264_39
Shoplifting007_x264_40
Shoplifting007_x264_41
Shoplifting007_x264_42
Shoplifting008_x264_0
Shoplifting008_x264_1
Shoplifting008_x264_2
Shoplifting008_x264_3
Shoplifting008_x264_4
Shoplifting008_x264_5
Shoplifting008_x264_6
Shoplifting008_x264_7
Shoplifting008_x264_8
Shoplifting008_x264_9
Shoplifting008_x264_10
Shoplifting008_x264_11
Shoplifting008_x264_12
Shoplifting008_x264_13
Shoplifting008_x264_14
Shoplifting008_x264_15
Shoplifting008_x264_16
Shoplifting008_x264_17
Shoplifting008_x264_18
Shoplifting008_x264_19
Shoplifting008_x264_20
Shoplifting008_x264_21
Shoplifting008_x264_22
Shoplifting008_x264_23
Shoplifting008_x264_24
Shoplifting008_x264_25
Shoplifting008_x264_26
Shoplifting008_x264_27
Shoplifting008_x264_28
Shoplifting008_x264_29
Shoplifting008_x264_30
Shoplifting008_x264_31
Shoplifting008_x264_32
Shoplifting008_x264_33
Shoplifting008_x264_34
Shoplifting008_x264_35
Shoplifting008_x264_36
Shoplifting008_x264_37
Shoplifting008_x264_38
Shoplifting008_x264_39
Shoplifting008_x264_40
Shoplifting008_x264_41
Shoplifting008_x264_46
Shoplifting008_x264_47
Shoplifting008_x264_48
Shoplifting008_x264_49
Shoplifting008_x264_50
Shoplifting008_x264_51
Shoplifting008_x264_52
Shoplifting008_x264_53
Shoplifting008_x264_54
Shoplifting008_x264_55
Shoplifting008_x264_56
Shoplifting008_x264_57
Shoplifting008_x264_58
Shoplifting008_x264_59
Shoplifting008_x264_60
Shoplifting008_x264_61
Shoplifting008_x264_62
Shoplifting008_x264_63
Shoplifting008_x264_64
Shoplifting008_x264_65
Shoplifting008_x264_66
Shoplifting008_x264_67
Shoplifting008_x264_68
Shoplifting008_x264_69
Shoplifting008_x264_70
Shoplifting008_x264_71
Shoplifting008_x264_72
Shoplifting008_x264_73
Shoplifting008_x264_74
Shoplifting009_x264_0
Shoplifting009_x264_1
Shoplifting009_x264_2
Shoplifting009_x264_3
Shoplifting009_x264_4
Shoplifting009_x264_5
Shoplifting009_x264_6
Shoplifting009_x264_7
Shoplifting009_x264_8
Shoplifting009_x264_9
Shoplifting009_x264_10
Shoplifting009_x264_11
Shoplifting009_x264_12
Shoplifting009_x264_13
Shoplifting009_x264_14
Shoplifting009_x264_15
Shoplifting009_x264_16
Shoplifting009_x264_17
Shoplifting009_x264_18
Shoplifting009_x264_19
Shoplifting009_x264_20
Shoplifting009_x264_21
Shoplifting009_x264_22
Shoplifting009_x264_23
Shoplifting009_x264_24
Shoplifting009_x264_25
Shoplifting009_x264_26
Shoplifting009_x264_27
Shoplifting009_x264_28
Shoplifting009_x264_29
Shoplifting009_x264_30
Shoplifting009_x264_31
Shoplifting009_x264_32
Shoplifting009_x264_33
Shoplifting009_x264_34
Shoplifting009_x264_35
Shoplifting009_x264_43
Shoplifting010_x264_0
Shoplifting010_x264_1
Shoplifting010_x264_2
Shoplifting010_x264_3
Shoplifting010_x264_4
Shoplifting010_x264_9
Shoplifting010_x264_10
Shoplifting010_x264_11
Shoplifting010_x264_12
Shoplifting010_x264_13
Shoplifting010_x264_14
Shoplifting010_x264_15
Shoplifting010_x264_16
Shoplifting010_x264_17
Shoplifting010_x264_18
Shoplifting010_x264_19
Shoplifting010_x264_20
Shoplifting010_x264_21
Shoplifting010_x264_22
Shoplifting012_x264_0
Shoplifting012_x264_1
Shoplifting012_x264_2
Shoplifting012_x264_3
Shoplifting012_x264_4
Shoplifting012_x264_5
Shoplifting012_x264_6
Shoplifting012_x264_7
Shoplifting012_x264_8
Shoplifting012_x264_9
Shoplifting012_x264_10
Shoplifting012_x264_11
Shoplifting012_x264_12
Shoplifting012_x264_13
Shoplifting012_x264_14
Shoplifting012_x264_15
Shoplifting012_x264_16
Shoplifting012_x264_17
Shoplifting012_x264_18
Shoplifting012_x264_19
Shoplifting012_x264_20
Shoplifting012_x264_21
Shoplifting012_x264_22
Shoplifting012_x264_23
Shoplifting012_x264_24
Shoplifting012_x264_25
Shoplifting012_x264_26
Shoplifting012_x264_27
Shoplifting012_x264_28
Shoplifting012_x264_29
Shoplifting012_x264_30
Shoplifting012_x264_31
Shoplifting012_x264_32
Shoplifting012_x264_33
Shoplifting012_x264_34
Shoplifting012_x264_35
Shoplifting012_x264_36
Shoplifting012_x264_37
Shoplifting012_x264_38
Shoplifting012_x264_39
Shoplifting012_x264_40
Shoplifting012_x264_41
Shoplifting012_x264_42
Shoplifting012_x264_43
Shoplifting012_x264_44
Shoplifting012_x264_45
Shoplifting012_x264_46
Shoplifting012_x264_47
Shoplifting012_x264_48
Shoplifting012_x264_49
Shoplifting012_x264_50
Shoplifting012_x264_51
Shoplifting012_x264_52
Shoplifting012_x264_53
Shoplifting012_x264_54
Shoplifting012_x264_55
Shoplifting012_x264_56
Shoplifting012_x264_57
Shoplifting012_x264_58
Shoplifting012_x264_59
Shoplifting012_x264_60
Shoplifting012_x264_61
Shoplifting012_x264_62
Shoplifting012_x264_63
Shoplifting012_x264_64
Shoplifting012_x264_65
Shoplifting012_x264_69
Shoplifting012_x264_70
Shoplifting012_x264_71
Shoplifting012_x264_72
Shoplifting012_x264_73
Shoplifting012_x264_74
Shoplifting012_x264_75
Shoplifting012_x264_76
Shoplifting012_x264_77
Shoplifting012_x264_78
Shoplifting012_x264_79
Shoplifting012_x264_80
Shoplifting012_x264_81
Shoplifting012_x264_82
Shoplifting012_x264_83
Shoplifting012_x264_84
Shoplifting012_x264_85
Shoplifting012_x264_86
Shoplifting012_x264_87
Shoplifting012_x264_93
Shoplifting012_x264_94
Shoplifting012_x264_95
Shoplifting012_x264_96
Shoplifting012_x264_97
Shoplifting012_x264_98
Shoplifting012_x264_99
Shoplifting012_x264_100
Shoplifting012_x264_101
Shoplifting012_x264_102
Shoplifting012_x264_103
Shoplifting012_x264_104
Shoplifting012_x264_105
Shoplifting012_x264_106
Shoplifting012_x264_107
Shoplifting012_x264_108
Shoplifting012_x264_109
Shoplifting012_x264_110
Shoplifting012_x264_111
Shoplifting012_x264_112
Shoplifting012_x264_113
Shoplifting012_x264_114
Shoplifting012_x264_115
Shoplifting012_x264_116
Shoplifting012_x264_117
Shoplifting012_x264_118
Shoplifting012_x264_119
Shoplifting012_x264_120
Shoplifting012_x264_121
Shoplifting012_x264_122
Shoplifting012_x264_123
Shoplifting012_x264_124
Shoplifting012_x264_125
Shoplifting012_x264_126
Shoplifting012_x264_127
Shoplifting012_x264_128
Shoplifting012_x264_129
Shoplifting012_x264_130
Shoplifting012_x264_131
Shoplifting012_x264_132
Shoplifting012_x264_133
Shoplifting012_x264_134
Shoplifting012_x264_135
Shoplifting012_x264_136
Shoplifting012_x264_137
Shoplifting012_x264_138
Shoplifting012_x264_139
Shoplifting012_x264_140
Shoplifting012_x264_141
Shoplifting012_x264_142
Shoplifting012_x264_143
Shoplifting012_x264_144
Shoplifting012_x264_145
Shoplifting012_x264_146
Shoplifting012_x264_147
Shoplifting012_x264_148
Shoplifting012_x264_149
Shoplifting012_x264_150
Shoplifting012_x264_151
Shoplifting012_x264_152
Shoplifting012_x264_153
Shoplifting012_x264_154
Shoplifting012_x264_155
Shoplifting012_x264_156
Shoplifting012_x264_157
Shoplifting012_x264_158
Shoplifting012_x264_159
Shoplifting012_x264_160
Shoplifting012_x264_161
Shoplifting012_x264_162
Shoplifting012_x264_163
Shoplifting012_x264_164
Shoplifting012_x264_165
Shoplifting012_x264_166
Shoplifting012_x264_167
Shoplifting012_x264_168
Shoplifting012_x264_169
Shoplifting012_x264_170
Shoplifting012_x264_171
Shoplifting012_x264_172
Shoplifting012_x264_173
Shoplifting012_x264_174
Shoplifting012_x264_175
Shoplifting012_x264_176
Shoplifting012_x264_177
Shoplifting012_x264_178
Shoplifting012_x264_179
Shoplifting012_x264_180
Shoplifting012_x264_181
Shoplifting012_x264_182

In [ ]:
#code to create ids_csv for training
ids_df = pd.DataFrame(columns=["Clip", "Parent Video", "ID", "Label", "Has Required"])
clips = pd.read_csv(f"{output_path}/shoplifting_ids.csv")
clips["List of Shoplifter ID"] = clips["List of Shoplifter ID"].fillna("[]")
for i in range(len(clips)):
  row = clips.iloc[i]
  new_row = {}
  clip = row["Clip"]
  print(clip)
  parent = row["Parent Video"]
  label = row["Label"]
  if label == 1:
    ids = json.loads(row["List of Shoplifter ID"])
  elif label == 0:
    ids = json.loads(row["List of Unique ID"])
  else:
    continue
  for id in ids:
    new_row["Clip"] = clip
    new_row["Parent Video"] = parent
    new_row["ID"] = id
    new_row["Label"] = label

    ids_df.loc[len(ids_df)] = new_row

ids_df.to_csv(f"{output_path}/ids.csv", index=False)

Shoplifting038_x264_24
Shoplifting029_x264_18
Shoplifting001_x264_10
Shoplifting001_x264_11
Shoplifting001_x264_12
Shoplifting001_x264_13
Shoplifting001_x264_14
Shoplifting001_x264_15
Shoplifting001_x264_16
Shoplifting003_x264_56
Shoplifting003_x264_57
Shoplifting003_x264_58
Shoplifting003_x264_59
Shoplifting003_x264_60
Shoplifting003_x264_61
Shoplifting003_x264_62
Shoplifting003_x264_63
Shoplifting004_x264_38
Shoplifting004_x264_39
Shoplifting004_x264_40
Shoplifting004_x264_41
Shoplifting005_x264_6
Shoplifting005_x264_7
Shoplifting006_x264_10
Shoplifting006_x264_11
Shoplifting006_x264_12
Shoplifting006_x264_13
Shoplifting006_x264_14
Shoplifting007_x264_4
Shoplifting007_x264_5
Shoplifting007_x264_6
Shoplifting007_x264_7
Shoplifting007_x264_8
Shoplifting008_x264_42
Shoplifting008_x264_43
Shoplifting008_x264_44
Shoplifting008_x264_45
Shoplifting009_x264_36
Shoplifting009_x264_37
Shoplifting009_x264_38
Shoplifting009_x264_39
Shoplifting009_x264_40
Shoplifting009_x264_41
Shoplifting009_x264_42
Shoplifting010_x264_5
Shoplifting010_x264_6
Shoplifting010_x264_7
Shoplifting010_x264_8
Shoplifting012_x264_66
Shoplifting012_x264_67
Shoplifting012_x264_68
Shoplifting012_x264_88
Shoplifting012_x264_89
Shoplifting012_x264_90
Shoplifting012_x264_91
Shoplifting012_x264_92
Shoplifting013_x264_1
Shoplifting013_x264_2
Shoplifting013_x264_3
Shoplifting013_x264_4
Shoplifting013_x264_5
Shoplifting013_x264_6
Shoplifting013_x264_7
Shoplifting013_x264_8
Shoplifting013_x264_9
Shoplifting013_x264_10
Shoplifting013_x264_11
Shoplifting013_x264_12
Shoplifting013_x264_13
Shoplifting013_x264_14
Shoplifting013_x264_15
Shoplifting013_x264_16
Shoplifting014_x264_178
Shoplifting014_x264_179
Shoplifting014_x264_180
Shoplifting014_x264_280
Shoplifting014_x264_281
Shoplifting014_x264_282
Shoplifting014_x264_283
Shoplifting014_x264_284
Shoplifting014_x264_285
Shoplifting014_x264_414
Shoplifting014_x264_415
Shoplifting014_x264_416
Shoplifting014_x264_419
Shoplifting014_x264_420
Shoplifting014_x264_421
Shoplifting014_x264_422
Shoplifting014_x264_450
Shoplifting014_x264_451
Shoplifting014_x264_452
Shoplifting014_x264_453
Shoplifting014_x264_454
Shoplifting014_x264_455
Shoplifting014_x264_456
Shoplifting015_x264_16
Shoplifting015_x264_17
Shoplifting016_x264_4
Shoplifting016_x264_5
Shoplifting016_x264_6
Shoplifting017_x264_2
Shoplifting017_x264_3
Shoplifting018_x264_3
Shoplifting018_x264_4
Shoplifting018_x264_5
Shoplifting018_x264_6
Shoplifting018_x264_7
Shoplifting018_x264_8
Shoplifting018_x264_9
Shoplifting018_x264_10
Shoplifting018_x264_11
Shoplifting018_x264_12
Shoplifting019_x264_1
Shoplifting019_x264_2
Shoplifting019_x264_3
Shoplifting020_x264_18
Shoplifting020_x264_19
Shoplifting020_x264_20
Shoplifting021_x264_17
Shoplifting021_x264_18
Shoplifting022_x264_2
Shoplifting022_x264_3
Shoplifting022_x264_4
Shoplifting022_x264_5
Shoplifting022_x264_6
Shoplifting022_x264_7
Shoplifting022_x264_8
Shoplifting022_x264_9
Shoplifting022_x264_10
Shoplifting022_x264_11
Shoplifting022_x264_12
Shoplifting022_x264_13
Shoplifting022_x264_14
Shoplifting022_x264_15
Shoplifting022_x264_16
Shoplifting024_x264_6
Shoplifting024_x264_7
Shoplifting024_x264_8
Shoplifting025_x264_3
Shoplifting025_x264_4
Shoplifting025_x264_5
Shoplifting025_x264_6
Shoplifting026_x264_1
Shoplifting026_x264_2
Shoplifting026_x264_3
Shoplifting026_x264_4
Shoplifting026_x264_5
Shoplifting026_x264_6
Shoplifting026_x264_7
Shoplifting026_x264_8
Shoplifting026_x264_9
Shoplifting026_x264_10
Shoplifting027_x264_8
Shoplifting027_x264_9
Shoplifting028_x264_4
Shoplifting028_x264_5
Shoplifting028_x264_6
Shoplifting028_x264_7
Shoplifting028_x264_8
Shoplifting029_x264_9
Shoplifting029_x264_10
Shoplifting029_x264_11
Shoplifting029_x264_12
Shoplifting030_x264_135
Shoplifting030_x264_136
Shoplifting030_x264_137
Shoplifting030_x264_138
Shoplifting030_x264_139
Shoplifting030_x264_140
Shoplifting030_x264_141
Shoplifting031_x264_1
Shoplifting031_x264_2
Shoplifting031_x264_3
Shoplifting032_x264_7
Shoplifting032_x264_8
Shoplifting032_x264_9
Shoplifting033_x264_5
Shoplifting033_x264_6
Shoplifting034_x264_38
Shoplifting034_x264_39
Shoplifting034_x264_42
Shoplifting034_x264_43
Shoplifting034_x264_46
Shoplifting034_x264_47
Shoplifting034_x264_60
Shoplifting034_x264_61
Shoplifting034_x264_67
Shoplifting034_x264_68
Shoplifting034_x264_69
Shoplifting036_x264_25
Shoplifting036_x264_26
Shoplifting036_x264_27
Shoplifting036_x264_28
Shoplifting037_x264_8
Shoplifting037_x264_9
Shoplifting038_x264_12
Shoplifting038_x264_13
Shoplifting038_x264_20
Shoplifting038_x264_21
Shoplifting039_x264_17
Shoplifting039_x264_18
Shoplifting040_x264_15
Shoplifting040_x264_16
Shoplifting040_x264_37
Shoplifting040_x264_38
Shoplifting040_x264_39
Shoplifting040_x264_70
Shoplifting040_x264_71
Shoplifting040_x264_84
Shoplifting040_x264_85
Shoplifting040_x264_86
Shoplifting040_x264_108
Shoplifting040_x264_109
Shoplifting041_x264_17
Shoplifting041_x264_18
Shoplifting041_x264_56
Shoplifting041_x264_57
Shoplifting041_x264_58
Shoplifting041_x264_59
Shoplifting041_x264_60
Shoplifting041_x264_76
Shoplifting041_x264_77
Shoplifting042_x264_15
Shoplifting042_x264_16
Shoplifting042_x264_17
Shoplifting042_x264_18
Shoplifting042_x264_19
Shoplifting042_x264_20
Shoplifting042_x264_21
Shoplifting042_x264_22
Shoplifting042_x264_23
Shoplifting042_x264_24
Shoplifting043_x264_49
Shoplifting043_x264_50
Shoplifting043_x264_51
Shoplifting043_x264_52
Shoplifting043_x264_53
Shoplifting043_x264_54
Shoplifting043_x264_55
Shoplifting043_x264_56
Shoplifting043_x264_57
Shoplifting044_x264_86
Shoplifting044_x264_87
Shoplifting044_x264_88
Shoplifting044_x264_89
Shoplifting044_x264_90
Shoplifting044_x264_91
Shoplifting044_x264_92
Shoplifting044_x264_93
Shoplifting044_x264_94
Shoplifting044_x264_95
Shoplifting044_x264_96
Shoplifting045_x264_5
Shoplifting045_x264_6
Shoplifting045_x264_7
Shoplifting045_x264_8
Shoplifting045_x264_9
Shoplifting045_x264_10
Shoplifting045_x264_11
Shoplifting045_x264_12
Shoplifting047_x264_9
Shoplifting047_x264_10
Shoplifting047_x264_11
Shoplifting047_x264_13
Shoplifting047_x264_14
Shoplifting047_x264_15
Shoplifting047_x264_16
Shoplifting047_x264_17
Shoplifting047_x264_18
Shoplifting047_x264_19
Shoplifting048_x264_1
Shoplifting048_x264_2
Shoplifting048_x264_7
Shoplifting048_x264_8
Shoplifting048_x264_9
Shoplifting049_x264_8
Shoplifting049_x264_9
Shoplifting049_x264_10
Shoplifting049_x264_11
Shoplifting050_x264_0
Shoplifting050_x264_1
Shoplifting050_x264_2
Shoplifting050_x264_3
Shoplifting050_x264_4
Shoplifting050_x264_5
Shoplifting050_x264_6
Shoplifting050_x264_7
Shoplifting050_x264_8
Shoplifting050_x264_9
Shoplifting050_x264_10
Shoplifting050_x264_11
Shoplifting050_x264_12
Shoplifting050_x264_13
Shoplifting050_x264_14
Shoplifting050_x264_15
Shoplifting051_x264_38
Shoplifting051_x264_39
Shoplifting051_x264_40
Shoplifting051_x264_41
Shoplifting051_x264_42
Shoplifting051_x264_43
Shoplifting052_x264_6
Shoplifting052_x264_7
Shoplifting052_x264_8
Shoplifting052_x264_13
Shoplifting052_x264_14
Shoplifting052_x264_15
Shoplifting052_x264_22
Shoplifting052_x264_23
Shoplifting052_x264_32
Shoplifting052_x264_33
Shoplifting052_x264_39
Shoplifting052_x264_40
Shoplifting052_x264_41
Shoplifting053_x264_10
Shoplifting053_x264_11
Shoplifting053_x264_12
Shoplifting053_x264_13
Shoplifting054_x264_4
Shoplifting054_x264_5
Shoplifting054_x264_6
Shoplifting055_x264_17
Shoplifting055_x264_18
Shoplifting055_x264_19
Shoplifting055_x264_20
Shoplifting055_x264_21
Shoplifting055_x264_22
Shoplifting055_x264_23
Shoplifting055_x264_24
Shoplifting055_x264_25
nan
Shoplifting001_x264_0
Shoplifting001_x264_1
Shoplifting001_x264_2
Shoplifting001_x264_3
Shoplifting001_x264_4
Shoplifting001_x264_5
Shoplifting001_x264_6
Shoplifting001_x264_7
Shoplifting001_x264_8
Shoplifting001_x264_9
Shoplifting001_x264_17
Shoplifting001_x264_18
Shoplifting001_x264_19
Shoplifting001_x264_20
Shoplifting001_x264_21
Shoplifting001_x264_22
Shoplifting001_x264_23
Shoplifting001_x264_24
Shoplifting001_x264_25
Shoplifting001_x264_26
Shoplifting001_x264_27
Shoplifting001_x264_28
Shoplifting001_x264_29
Shoplifting001_x264_30
Shoplifting001_x264_31
Shoplifting001_x264_32
Shoplifting001_x264_33
Shoplifting001_x264_34
Shoplifting001_x264_35
Shoplifting001_x264_36
Shoplifting003_x264_0
Shoplifting003_x264_1
Shoplifting003_x264_2
Shoplifting003_x264_3
Shoplifting003_x264_4
Shoplifting003_x264_5
Shoplifting003_x264_6
Shoplifting003_x264_7
Shoplifting003_x264_8
Shoplifting003_x264_9
Shoplifting003_x264_10
Shoplifting003_x264_11
Shoplifting003_x264_12
Shoplifting003_x264_13
Shoplifting003_x264_14
Shoplifting003_x264_15
Shoplifting003_x264_16
Shoplifting003_x264_17
Shoplifting003_x264_18
Shoplifting003_x264_19
Shoplifting003_x264_20
Shoplifting003_x264_21
Shoplifting003_x264_22
Shoplifting003_x264_23
Shoplifting003_x264_24
Shoplifting003_x264_25
Shoplifting003_x264_26
Shoplifting003_x264_27
Shoplifting003_x264_28
Shoplifting003_x264_29
Shoplifting003_x264_30
Shoplifting003_x264_31
Shoplifting003_x264_32
Shoplifting003_x264_33
Shoplifting003_x264_34
Shoplifting003_x264_35
Shoplifting003_x264_36
Shoplifting003_x264_37
Shoplifting003_x264_38
Shoplifting003_x264_39
Shoplifting003_x264_40
Shoplifting003_x264_41
Shoplifting003_x264_42
Shoplifting003_x264_43
Shoplifting003_x264_44
Shoplifting003_x264_45
Shoplifting003_x264_46
Shoplifting003_x264_47
Shoplifting003_x264_48
Shoplifting003_x264_49
Shoplifting003_x264_50
Shoplifting003_x264_51
Shoplifting003_x264_52
Shoplifting003_x264_53
Shoplifting003_x264_54
Shoplifting003_x264_55
Shoplifting003_x264_64
Shoplifting003_x264_65
Shoplifting003_x264_66
Shoplifting003_x264_67
Shoplifting003_x264_68
Shoplifting003_x264_69
Shoplifting003_x264_70
Shoplifting003_x264_71
Shoplifting003_x264_72
Shoplifting003_x264_73
Shoplifting003_x264_74
Shoplifting003_x264_75
Shoplifting003_x264_76
Shoplifting003_x264_77
Shoplifting003_x264_78
Shoplifting003_x264_79
Shoplifting003_x264_80
Shoplifting003_x264_81
Shoplifting003_x264_82
Shoplifting003_x264_83
Shoplifting003_x264_84
Shoplifting003_x264_85
Shoplifting003_x264_86
Shoplifting003_x264_87
Shoplifting003_x264_88
Shoplifting003_x264_89
Shoplifting003_x264_90
Shoplifting004_x264_0
Shoplifting004_x264_1
Shoplifting004_x264_2
Shoplifting004_x264_3
Shoplifting004_x264_4
Shoplifting004_x264_5
Shoplifting004_x264_6
Shoplifting004_x264_7
Shoplifting004_x264_8
Shoplifting004_x264_9
Shoplifting004_x264_10
Shoplifting004_x264_11
Shoplifting004_x264_12
Shoplifting004_x264_13
Shoplifting004_x264_14
Shoplifting004_x264_15
Shoplifting004_x264_16
Shoplifting004_x264_17
Shoplifting004_x264_18
Shoplifting004_x264_19
Shoplifting004_x264_20
Shoplifting004_x264_21
Shoplifting004_x264_22
Shoplifting004_x264_23
Shoplifting004_x264_24
Shoplifting004_x264_25
Shoplifting004_x264_26
Shoplifting004_x264_27
Shoplifting004_x264_28
Shoplifting004_x264_29
Shoplifting004_x264_30
Shoplifting004_x264_31
Shoplifting004_x264_32
Shoplifting004_x264_33
Shoplifting004_x264_34
Shoplifting004_x264_35
Shoplifting004_x264_36
Shoplifting004_x264_37
Shoplifting004_x264_42
Shoplifting004_x264_43
Shoplifting004_x264_44
Shoplifting004_x264_45
Shoplifting004_x264_46
Shoplifting004_x264_47
Shoplifting004_x264_48
Shoplifting004_x264_49
Shoplifting004_x264_50
Shoplifting004_x264_51
Shoplifting004_x264_52
Shoplifting004_x264_53
Shoplifting004_x264_54
Shoplifting004_x264_55
Shoplifting005_x264_0
Shoplifting005_x264_1
Shoplifting005_x264_2
Shoplifting005_x264_3
Shoplifting005_x264_4
Shoplifting005_x264_5
Shoplifting005_x264_8
Shoplifting005_x264_9
Shoplifting005_x264_10
Shoplifting005_x264_11
Shoplifting005_x264_12
Shoplifting005_x264_13
Shoplifting005_x264_14
Shoplifting005_x264_15
Shoplifting005_x264_16
Shoplifting006_x264_0
Shoplifting006_x264_1
Shoplifting006_x264_2
Shoplifting006_x264_3
Shoplifting006_x264_4
Shoplifting006_x264_5
Shoplifting006_x264_6
Shoplifting006_x264_7
Shoplifting006_x264_8
Shoplifting006_x264_9
Shoplifting006_x264_15
Shoplifting006_x264_16
Shoplifting006_x264_17
Shoplifting006_x264_18
Shoplifting006_x264_19
Shoplifting006_x264_20
Shoplifting006_x264_21
Shoplifting006_x264_22
Shoplifting006_x264_23
Shoplifting006_x264_24
Shoplifting006_x264_25
Shoplifting006_x264_26
Shoplifting007_x264_0
Shoplifting007_x264_1
Shoplifting007_x264_2
Shoplifting007_x264_3
Shoplifting007_x264_9
Shoplifting007_x264_10
Shoplifting007_x264_11
Shoplifting007_x264_12
Shoplifting007_x264_13
Shoplifting007_x264_14
Shoplifting007_x264_15
Shoplifting007_x264_16
Shoplifting007_x264_17
Shoplifting007_x264_18
Shoplifting007_x264_19
Shoplifting007_x264_20
Shoplifting007_x264_21
Shoplifting007_x264_22
Shoplifting007_x264_23
Shoplifting007_x264_24
Shoplifting007_x264_25
Shoplifting007_x264_26
Shoplifting007_x264_27
Shoplifting007_x264_28
Shoplifting007_x264_29
Shoplifting007_x264_30
Shoplifting007_x264_31
Shoplifting007_x264_32
Shoplifting007_x264_33
Shoplifting007_x264_34
Shoplifting007_x264_35
Shoplifting007_x264_36
Shoplifting007_x264_37
Shoplifting007_x264_38
Shoplifting007_x264_39
Shoplifting007_x264_40
Shoplifting007_x264_41
Shoplifting007_x264_42
Shoplifting008_x264_0
Shoplifting008_x264_1
Shoplifting008_x264_2
Shoplifting008_x264_3
Shoplifting008_x264_4
Shoplifting008_x264_5
Shoplifting008_x264_6
Shoplifting008_x264_7
Shoplifting008_x264_8
Shoplifting008_x264_9
Shoplifting008_x264_10
Shoplifting008_x264_11
Shoplifting008_x264_12
Shoplifting008_x264_13
Shoplifting008_x264_14
Shoplifting008_x264_15
Shoplifting008_x264_16
Shoplifting008_x264_17
Shoplifting008_x264_18
Shoplifting008_x264_19
Shoplifting008_x264_20
Shoplifting008_x264_21
Shoplifting008_x264_22
Shoplifting008_x264_23
Shoplifting008_x264_24
Shoplifting008_x264_25
Shoplifting008_x264_26
Shoplifting008_x264_27
Shoplifting008_x264_28
Shoplifting008_x264_29
Shoplifting008_x264_30
Shoplifting008_x264_31
Shoplifting008_x264_32
Shoplifting008_x264_33
Shoplifting008_x264_34
Shoplifting008_x264_35
Shoplifting008_x264_36
Shoplifting008_x264_37
Shoplifting008_x264_38
Shoplifting008_x264_39
Shoplifting008_x264_40
Shoplifting008_x264_41
Shoplifting008_x264_46
Shoplifting008_x264_47
Shoplifting008_x264_48
Shoplifting008_x264_49
Shoplifting008_x264_50
Shoplifting008_x264_51
Shoplifting008_x264_52
Shoplifting008_x264_53
Shoplifting008_x264_54
Shoplifting008_x264_55
Shoplifting008_x264_56
Shoplifting008_x264_57
Shoplifting008_x264_58
Shoplifting008_x264_59
Shoplifting008_x264_60
Shoplifting008_x264_61
Shoplifting008_x264_62
Shoplifting008_x264_63
Shoplifting008_x264_64
Shoplifting008_x264_65
Shoplifting008_x264_66
Shoplifting008_x264_67
Shoplifting008_x264_68
Shoplifting008_x264_69
Shoplifting008_x264_70
Shoplifting008_x264_71
Shoplifting008_x264_72
Shoplifting008_x264_73
Shoplifting008_x264_74
Shoplifting009_x264_0
Shoplifting009_x264_1
Shoplifting009_x264_2
Shoplifting009_x264_3
Shoplifting009_x264_4
Shoplifting009_x264_5
Shoplifting009_x264_6
Shoplifting009_x264_7
Shoplifting009_x264_8
Shoplifting009_x264_9
Shoplifting009_x264_10
Shoplifting009_x264_11
Shoplifting009_x264_12
Shoplifting009_x264_13
Shoplifting009_x264_14
Shoplifting009_x264_15
Shoplifting009_x264_16
Shoplifting009_x264_17
Shoplifting009_x264_18
Shoplifting009_x264_19
Shoplifting009_x264_20
Shoplifting009_x264_21
Shoplifting009_x264_22
Shoplifting009_x264_23
Shoplifting009_x264_24
Shoplifting009_x264_25
Shoplifting009_x264_26
Shoplifting009_x264_27
Shoplifting009_x264_28
Shoplifting009_x264_29
Shoplifting009_x264_30
Shoplifting009_x264_31
Shoplifting009_x264_32
Shoplifting009_x264_33
Shoplifting009_x264_34
Shoplifting009_x264_35
Shoplifting009_x264_43
Shoplifting010_x264_0
Shoplifting010_x264_1
Shoplifting010_x264_2
Shoplifting010_x264_3
Shoplifting010_x264_4
Shoplifting010_x264_9
Shoplifting010_x264_10
Shoplifting010_x264_11
Shoplifting010_x264_12
Shoplifting010_x264_13
Shoplifting010_x264_14
Shoplifting010_x264_15
Shoplifting010_x264_16
Shoplifting010_x264_17
Shoplifting010_x264_18
Shoplifting010_x264_19
Shoplifting010_x264_20
Shoplifting010_x264_21
Shoplifting010_x264_22
Shoplifting012_x264_0
Shoplifting012_x264_1
Shoplifting012_x264_2
Shoplifting012_x264_3
Shoplifting012_x264_4
Shoplifting012_x264_5
Shoplifting012_x264_6
Shoplifting012_x264_7
Shoplifting012_x264_8
Shoplifting012_x264_9
Shoplifting012_x264_10
Shoplifting012_x264_11
Shoplifting012_x264_12
Shoplifting012_x264_13
Shoplifting012_x264_14
Shoplifting012_x264_15
Shoplifting012_x264_16
Shoplifting012_x264_17
Shoplifting012_x264_18
Shoplifting012_x264_19
Shoplifting012_x264_20
Shoplifting012_x264_21
Shoplifting012_x264_22
Shoplifting012_x264_23
Shoplifting012_x264_24
Shoplifting012_x264_25
Shoplifting012_x264_26
Shoplifting012_x264_27
Shoplifting012_x264_28
Shoplifting012_x264_29
Shoplifting012_x264_30
Shoplifting012_x264_31
Shoplifting012_x264_32
Shoplifting012_x264_33
Shoplifting012_x264_34
Shoplifting012_x264_35
Shoplifting012_x264_36
Shoplifting012_x264_37
Shoplifting012_x264_38
Shoplifting012_x264_39
Shoplifting012_x264_40
Shoplifting012_x264_41
Shoplifting012_x264_42
Shoplifting012_x264_43
Shoplifting012_x264_44
Shoplifting012_x264_45
Shoplifting012_x264_46
Shoplifting012_x264_47
Shoplifting012_x264_48
Shoplifting012_x264_49
Shoplifting012_x264_50
Shoplifting012_x264_51
Shoplifting012_x264_52
Shoplifting012_x264_53
Shoplifting012_x264_54
Shoplifting012_x264_55
Shoplifting012_x264_56
Shoplifting012_x264_57
Shoplifting012_x264_58
Shoplifting012_x264_59
Shoplifting012_x264_60
Shoplifting012_x264_61
Shoplifting012_x264_62
Shoplifting012_x264_63
Shoplifting012_x264_64
Shoplifting012_x264_65
Shoplifting012_x264_69
Shoplifting012_x264_70
Shoplifting012_x264_71
Shoplifting012_x264_72
Shoplifting012_x264_73
Shoplifting012_x264_74
Shoplifting012_x264_75
Shoplifting012_x264_76
Shoplifting012_x264_77
Shoplifting012_x264_78
Shoplifting012_x264_79
Shoplifting012_x264_80
Shoplifting012_x264_81
Shoplifting012_x264_82
Shoplifting012_x264_83
Shoplifting012_x264_84
Shoplifting012_x264_85
Shoplifting012_x264_86
Shoplifting012_x264_87
Shoplifting012_x264_93
Shoplifting012_x264_94
Shoplifting012_x264_95
Shoplifting012_x264_96
Shoplifting012_x264_97
Shoplifting012_x264_98
Shoplifting012_x264_99
Shoplifting012_x264_100
Shoplifting012_x264_101
Shoplifting012_x264_102
Shoplifting012_x264_103
Shoplifting012_x264_104
Shoplifting012_x264_105
Shoplifting012_x264_106
Shoplifting012_x264_107
Shoplifting012_x264_108
Shoplifting012_x264_109
Shoplifting012_x264_110
Shoplifting012_x264_111
Shoplifting012_x264_112
Shoplifting012_x264_113
Shoplifting012_x264_114
Shoplifting012_x264_115
Shoplifting012_x264_116
Shoplifting012_x264_117
Shoplifting012_x264_118
Shoplifting012_x264_119
Shoplifting012_x264_120
Shoplifting012_x264_121
Shoplifting012_x264_122
Shoplifting012_x264_123
Shoplifting012_x264_124
Shoplifting012_x264_125
Shoplifting012_x264_126
Shoplifting012_x264_127
Shoplifting012_x264_128
Shoplifting012_x264_129
Shoplifting012_x264_130
Shoplifting012_x264_131
Shoplifting012_x264_132
Shoplifting012_x264_133
Shoplifting012_x264_134
Shoplifting012_x264_135
Shoplifting012_x264_136
Shoplifting012_x264_137
Shoplifting012_x264_138
Shoplifting012_x264_139
Shoplifting012_x264_140
Shoplifting012_x264_141
Shoplifting012_x264_142
Shoplifting012_x264_143
Shoplifting012_x264_144
Shoplifting012_x264_145
Shoplifting012_x264_146
Shoplifting012_x264_147
Shoplifting012_x264_148
Shoplifting012_x264_149
Shoplifting012_x264_150
Shoplifting012_x264_151
Shoplifting012_x264_152
Shoplifting012_x264_153
Shoplifting012_x264_154
Shoplifting012_x264_155
Shoplifting012_x264_156
Shoplifting012_x264_157
Shoplifting012_x264_158
Shoplifting012_x264_159
Shoplifting012_x264_160
Shoplifting012_x264_161
Shoplifting012_x264_162
Shoplifting012_x264_163
Shoplifting012_x264_164
Shoplifting012_x264_165
Shoplifting012_x264_166
Shoplifting012_x264_167
Shoplifting012_x264_168
Shoplifting012_x264_169
Shoplifting012_x264_170
Shoplifting012_x264_171
Shoplifting012_x264_172
Shoplifting012_x264_173
Shoplifting012_x264_174
Shoplifting012_x264_175
Shoplifting012_x264_176
Shoplifting012_x264_177
Shoplifting012_x264_178
Shoplifting012_x264_179
Shoplifting012_x264_180
Shoplifting012_x264_181
Shoplifting012_x264_182

In [ ]:
ids_df = pd.read_csv(f"{output_path}/ids.csv")
counts = ids_df["Has Required"].map(lambda s: len(json.loads(s)))
print(len(ids_df))
ids_df = ids_df[counts >= 50]
print(len(ids_df))

5558
1200

In [ ]:
n_frames = 120
total_features = 2 * len(joint_indices_required) * n_frames + 2 * len(joint_indices_required) * (n_frames - 1) + len(pairs) * n_frames + len(pairs) * n_frames
print(total_features)
for i in range(len(ids_df)):
  row = ids_df.iloc[i]
  person_path = f"{yolo_path}/{row['Parent Video']}/{row['Clip']}/scaled_person_{row['ID']}.json"
  good_frames = json.loads(row["Has Required"])
  with open(person_path) as f:
    padded_after = get_feature_vector(f, good_frames, padding="after")
    assert len(padded_after) == total_features, f"Vector is of length {len(padded_after)}, expected {total_features}"
  with open(person_path) as f:
    padded_between = get_feature_vector(f, good_frames, padding="between")
    assert len(padded_between) == total_features, f"Vector is of length {len(padded_between)}, expected {total_features}"

7178

In [ ]:
def feature_vector_from_row(row):
  person_path = f"{yolo_path}/{row['Parent Video']}/{row['Clip']}/persons/person_{row['ID']}/keypoints_0.json"
  good_frames = row["Has Required"]
  with open(person_path) as f:
    vector = get_feature_vector(f, good_frames, padding="after")
  return vector

def get_good_frames(row):
  print(f"processing {row['Clip']}; person id: {row['ID']}")
  person_path = f"{yolo_path}/{row['Parent Video']}/{row['Clip']}/persons/person_{row['ID']}/keypoints_0.json"
  with open(person_path) as f:
    person = json.load(f)
  add_missing(person)
  required = []
  for frame in person:
    keypoints = person[frame][0]["keypoints"]
    #if has_required(keypoints):
    if has_neck(keypoints):
      required.append(frame[frame.find('_')+1:])
  return required


ids_df = pd.read_csv(f"{output_path}/ids.csv")
ids_df["Has Required"] = ids_df.apply(get_good_frames, axis=1)
counts = ids_df["Has Required"].map(len)
ids_df = ids_df[counts > 0]
feature_df = pd.DataFrame()
feature_df["clip"] = ids_df["Clip"]
feature_df["parent"] = ids_df["Parent Video"]
feature_df["id"] = ids_df["ID"]
feature_df["features"] = ids_df.apply(feature_vector_from_row, axis=1)
feature_df["target"] = ids_df["Label"]
print(len(feature_df), feature_df["target"].value_counts())
feature_df.to_csv(f"{output_path}/features_eyes.csv", index=False)
feature_df.head()

Streaming output truncated to the last 5000 lines.
processing Shoplifting003_x264_82; person id: 2
processing Shoplifting003_x264_83; person id: 1
processing Shoplifting003_x264_83; person id: 2
processing Shoplifting003_x264_84; person id: 1
processing Shoplifting003_x264_86; person id: 1
processing Shoplifting003_x264_86; person id: 2
processing Shoplifting003_x264_87; person id: 1
processing Shoplifting003_x264_87; person id: 2
processing Shoplifting003_x264_87; person id: 3
processing Shoplifting003_x264_88; person id: 1
processing Shoplifting003_x264_89; person id: 1
processing Shoplifting004_x264_0; person id: 1
processing Shoplifting004_x264_0; person id: 2
processing Shoplifting004_x264_0; person id: 3
processing Shoplifting004_x264_1; person id: 1
processing Shoplifting004_x264_1; person id: 2
processing Shoplifting004_x264_2; person id: 1
processing Shoplifting004_x264_2; person id: 2
processing Shoplifting004_x264_2; person id: 3
processing Shoplifting004_x264_3; person id: 1
processing Shoplifting004_x264_3; person id: 2
processing Shoplifting004_x264_4; person id: 1
processing Shoplifting004_x264_4; person id: 2
processing Shoplifting004_x264_4; person id: 3
processing Shoplifting004_x264_4; person id: 4
processing Shoplifting004_x264_5; person id: 1
processing Shoplifting004_x264_5; person id: 2
processing Shoplifting004_x264_5; person id: 4
processing Shoplifting004_x264_6; person id: 1
processing Shoplifting004_x264_6; person id: 2
processing Shoplifting004_x264_6; person id: 3
processing Shoplifting004_x264_6; person id: 4
processing Shoplifting004_x264_7; person id: 1
processing Shoplifting004_x264_7; person id: 3
processing Shoplifting004_x264_8; person id: 1
processing Shoplifting004_x264_8; person id: 2
processing Shoplifting004_x264_8; person id: 3
processing Shoplifting004_x264_8; person id: 4
processing Shoplifting004_x264_9; person id: 1
processing Shoplifting004_x264_9; person id: 3
processing Shoplifting004_x264_9; person id: 4
processing Shoplifting004_x264_9; person id: 5
processing Shoplifting004_x264_9; person id: 6
processing Shoplifting004_x264_9; person id: 7
processing Shoplifting004_x264_10; person id: 1
processing Shoplifting004_x264_10; person id: 2
processing Shoplifting004_x264_10; person id: 3
processing Shoplifting004_x264_11; person id: 1
processing Shoplifting004_x264_11; person id: 2
processing Shoplifting004_x264_11; person id: 3
processing Shoplifting004_x264_11; person id: 4
processing Shoplifting004_x264_11; person id: 6
processing Shoplifting004_x264_12; person id: 1
processing Shoplifting004_x264_12; person id: 2
processing Shoplifting004_x264_12; person id: 3
processing Shoplifting004_x264_13; person id: 1
processing Shoplifting004_x264_13; person id: 2
processing Shoplifting004_x264_13; person id: 5
processing Shoplifting004_x264_14; person id: 1
processing Shoplifting004_x264_14; person id: 3
processing Shoplifting004_x264_14; person id: 5
processing Shoplifting004_x264_14; person id: 7
processing Shoplifting004_x264_15; person id: 1
processing Shoplifting004_x264_15; person id: 2
processing Shoplifting004_x264_15; person id: 3
processing Shoplifting004_x264_16; person id: 1
processing Shoplifting004_x264_16; person id: 2
processing Shoplifting004_x264_16; person id: 3
processing Shoplifting004_x264_16; person id: 6
processing Shoplifting004_x264_17; person id: 1
processing Shoplifting004_x264_17; person id: 2
processing Shoplifting004_x264_17; person id: 3
processing Shoplifting004_x264_17; person id: 4
processing Shoplifting004_x264_17; person id: 6
processing Shoplifting004_x264_18; person id: 1
processing Shoplifting004_x264_18; person id: 2
processing Shoplifting004_x264_18; person id: 3
processing Shoplifting004_x264_18; person id: 4
processing Shoplifting004_x264_19; person id: 1
processing Shoplifting004_x264_19; person id: 2
processing Shoplifting004_x264_19; person id: 3
processing Shoplifting004_x264_19; person id: 4
processing Shoplifting004_x264_20; person id: 1
processing Shoplifting004_x264_20; person id: 2
processing Shoplifting004_x264_20; person id: 3
processing Shoplifting004_x264_20; person id: 4
processing Shoplifting004_x264_21; person id: 1
processing Shoplifting004_x264_21; person id: 2
processing Shoplifting004_x264_21; person id: 3
processing Shoplifting004_x264_21; person id: 4
processing Shoplifting004_x264_22; person id: 1
processing Shoplifting004_x264_22; person id: 2
processing Shoplifting004_x264_22; person id: 3
processing Shoplifting004_x264_22; person id: 4
processing Shoplifting004_x264_23; person id: 1
processing Shoplifting004_x264_23; person id: 2
processing Shoplifting004_x264_23; person id: 3
processing Shoplifting004_x264_23; person id: 4
processing Shoplifting004_x264_23; person id: 5
processing Shoplifting004_x264_24; person id: 1
processing Shoplifting004_x264_24; person id: 2
processing Shoplifting004_x264_24; person id: 3
processing Shoplifting004_x264_24; person id: 4
processing Shoplifting004_x264_25; person id: 1
processing Shoplifting004_x264_25; person id: 2
processing Shoplifting004_x264_25; person id: 3
processing Shoplifting004_x264_25; person id: 5
processing Shoplifting004_x264_26; person id: 1
processing Shoplifting004_x264_26; person id: 2
processing Shoplifting004_x264_26; person id: 3
processing Shoplifting004_x264_26; person id: 4
processing Shoplifting004_x264_26; person id: 6
processing Shoplifting004_x264_26; person id: 7
processing Shoplifting004_x264_27; person id: 1
processing Shoplifting004_x264_27; person id: 2
processing Shoplifting004_x264_27; person id: 3
processing Shoplifting004_x264_27; person id: 6
processing Shoplifting004_x264_27; person id: 7
processing Shoplifting004_x264_27; person id: 10
processing Shoplifting004_x264_28; person id: 1
processing Shoplifting004_x264_28; person id: 2
processing Shoplifting004_x264_28; person id: 3
processing Shoplifting004_x264_28; person id: 4
processing Shoplifting004_x264_28; person id: 6
processing Shoplifting004_x264_29; person id: 1
processing Shoplifting004_x264_29; person id: 2
processing Shoplifting004_x264_29; person id: 3
processing Shoplifting004_x264_29; person id: 8
processing Shoplifting004_x264_29; person id: 9
processing Shoplifting004_x264_30; person id: 1
processing Shoplifting004_x264_30; person id: 2
processing Shoplifting004_x264_30; person id: 3
processing Shoplifting004_x264_30; person id: 4
processing Shoplifting004_x264_30; person id: 5
processing Shoplifting004_x264_31; person id: 1
processing Shoplifting004_x264_31; person id: 2
processing Shoplifting004_x264_31; person id: 3
processing Shoplifting004_x264_31; person id: 4
processing Shoplifting004_x264_32; person id: 1
processing Shoplifting004_x264_32; person id: 2
processing Shoplifting004_x264_32; person id: 3
processing Shoplifting004_x264_32; person id: 4
processing Shoplifting004_x264_32; person id: 6
processing Shoplifting004_x264_33; person id: 1
processing Shoplifting004_x264_33; person id: 2
processing Shoplifting004_x264_33; person id: 3
processing Shoplifting004_x264_33; person id: 4
processing Shoplifting004_x264_34; person id: 1
processing Shoplifting004_x264_34; person id: 2
processing Shoplifting004_x264_34; person id: 3
processing Shoplifting004_x264_34; person id: 4
processing Shoplifting004_x264_35; person id: 1
processing Shoplifting004_x264_35; person id: 2
processing Shoplifting004_x264_35; person id: 3
processing Shoplifting004_x264_35; person id: 4
processing Shoplifting004_x264_35; person id: 5
processing Shoplifting004_x264_36; person id: 1
processing Shoplifting004_x264_36; person id: 2
processing Shoplifting004_x264_36; person id: 3
processing Shoplifting004_x264_36; person id: 4
processing Shoplifting004_x264_37; person id: 1
processing Shoplifting004_x264_37; person id: 2
processing Shoplifting004_x264_37; person id: 3
processing Shoplifting004_x264_37; person id: 4
processing Shoplifting004_x264_37; person id: 5
processing Shoplifting004_x264_42; person id: 1
processing Shoplifting004_x264_42; person id: 2
processing Shoplifting004_x264_43; person id: 1
processing Shoplifting004_x264_43; person id: 2
processing Shoplifting004_x264_44; person id: 1
processing Shoplifting004_x264_44; person id: 2
processing Shoplifting004_x264_44; person id: 4
processing Shoplifting004_x264_45; person id: 1
processing Shoplifting004_x264_45; person id: 2
processing Shoplifting004_x264_46; person id: 1
processing Shoplifting004_x264_46; person id: 2
processing Shoplifting004_x264_47; person id: 1
processing Shoplifting004_x264_47; person id: 2
processing Shoplifting004_x264_47; person id: 3
processing Shoplifting004_x264_47; person id: 4
processing Shoplifting004_x264_48; person id: 1
processing Shoplifting004_x264_48; person id: 2
processing Shoplifting004_x264_48; person id: 3
processing Shoplifting004_x264_48; person id: 4
processing Shoplifting004_x264_49; person id: 1
processing Shoplifting004_x264_49; person id: 2
processing Shoplifting004_x264_49; person id: 4
processing Shoplifting004_x264_49; person id: 7
processing Shoplifting004_x264_50; person id: 1
processing Shoplifting004_x264_50; person id: 2
processing Shoplifting004_x264_50; person id: 3
processing Shoplifting004_x264_50; person id: 4
processing Shoplifting004_x264_51; person id: 1
processing Shoplifting004_x264_51; person id: 2
processing Shoplifting004_x264_51; person id: 3
processing Shoplifting004_x264_52; person id: 1
processing Shoplifting004_x264_52; person id: 2
processing Shoplifting004_x264_52; person id: 4
processing Shoplifting004_x264_53; person id: 1
processing Shoplifting004_x264_53; person id: 2
processing Shoplifting004_x264_53; person id: 5
processing Shoplifting004_x264_54; person id: 1
processing Shoplifting004_x264_54; person id: 2
processing Shoplifting004_x264_54; person id: 4
processing Shoplifting004_x264_54; person id: 5
processing Shoplifting004_x264_55; person id: 1
processing Shoplifting004_x264_55; person id: 2
processing Shoplifting004_x264_55; person id: 3
processing Shoplifting004_x264_55; person id: 5
processing Shoplifting005_x264_0; person id: 1
processing Shoplifting005_x264_1; person id: 1
processing Shoplifting005_x264_1; person id: 2
processing Shoplifting005_x264_1; person id: 3
processing Shoplifting005_x264_2; person id: 1
processing Shoplifting005_x264_2; person id: 2
processing Shoplifting005_x264_2; person id: 3
processing Shoplifting005_x264_3; person id: 1
processing Shoplifting005_x264_3; person id: 2
processing Shoplifting005_x264_3; person id: 3
processing Shoplifting005_x264_4; person id: 1
processing Shoplifting005_x264_5; person id: 1
processing Shoplifting005_x264_5; person id: 2
processing Shoplifting005_x264_8; person id: 1
processing Shoplifting005_x264_9; person id: 1
processing Shoplifting005_x264_10; person id: 1
processing Shoplifting005_x264_11; person id: 1
processing Shoplifting005_x264_12; person id: 1
processing Shoplifting005_x264_13; person id: 1
processing Shoplifting005_x264_14; person id: 1
processing Shoplifting005_x264_14; person id: 2
processing Shoplifting005_x264_15; person id: 1
processing Shoplifting005_x264_15; person id: 2
processing Shoplifting005_x264_15; person id: 3
processing Shoplifting005_x264_16; person id: 1
processing Shoplifting005_x264_16; person id: 2
processing Shoplifting006_x264_0; person id: 1
processing Shoplifting006_x264_0; person id: 2
processing Shoplifting006_x264_1; person id: 1
processing Shoplifting006_x264_1; person id: 2
processing Shoplifting006_x264_2; person id: 1
processing Shoplifting006_x264_2; person id: 2
processing Shoplifting006_x264_3; person id: 1
processing Shoplifting006_x264_4; person id: 1
processing Shoplifting006_x264_5; person id: 1
processing Shoplifting006_x264_6; person id: 1
processing Shoplifting006_x264_8; person id: 1
processing Shoplifting006_x264_9; person id: 1
processing Shoplifting006_x264_9; person id: 2
processing Shoplifting006_x264_15; person id: 1
processing Shoplifting006_x264_15; person id: 2
processing Shoplifting006_x264_16; person id: 1
processing Shoplifting006_x264_16; person id: 2
processing Shoplifting006_x264_16; person id: 4
processing Shoplifting006_x264_16; person id: 5
processing Shoplifting006_x264_16; person id: 7
processing Shoplifting006_x264_17; person id: 1
processing Shoplifting006_x264_17; person id: 3
processing Shoplifting006_x264_17; person id: 4
processing Shoplifting006_x264_17; person id: 5
processing Shoplifting006_x264_18; person id: 1
processing Shoplifting006_x264_18; person id: 2
processing Shoplifting006_x264_19; person id: 1
processing Shoplifting006_x264_19; person id: 2
processing Shoplifting006_x264_19; person id: 4
processing Shoplifting006_x264_19; person id: 5
processing Shoplifting006_x264_19; person id: 6
processing Shoplifting006_x264_20; person id: 1
processing Shoplifting006_x264_20; person id: 2
processing Shoplifting006_x264_20; person id: 4
processing Shoplifting006_x264_21; person id: 1
processing Shoplifting006_x264_21; person id: 2
processing Shoplifting006_x264_22; person id: 1
processing Shoplifting006_x264_22; person id: 2
processing Shoplifting006_x264_22; person id: 3
processing Shoplifting006_x264_22; person id: 4
processing Shoplifting006_x264_22; person id: 5
processing Shoplifting006_x264_23; person id: 1
processing Shoplifting006_x264_23; person id: 2
processing Shoplifting006_x264_23; person id: 3
processing Shoplifting006_x264_23; person id: 4
processing Shoplifting006_x264_23; person id: 5
processing Shoplifting006_x264_23; person id: 6
processing Shoplifting006_x264_24; person id: 1
processing Shoplifting006_x264_24; person id: 2
processing Shoplifting006_x264_25; person id: 1
processing Shoplifting006_x264_25; person id: 2
processing Shoplifting007_x264_0; person id: 1
processing Shoplifting007_x264_0; person id: 3
processing Shoplifting007_x264_1; person id: 1
processing Shoplifting007_x264_1; person id: 2
processing Shoplifting007_x264_2; person id: 1
processing Shoplifting007_x264_2; person id: 2
processing Shoplifting007_x264_2; person id: 3
processing Shoplifting007_x264_3; person id: 1
processing Shoplifting007_x264_3; person id: 2
processing Shoplifting007_x264_3; person id: 3
processing Shoplifting007_x264_11; person id: 1
processing Shoplifting007_x264_11; person id: 2
processing Shoplifting007_x264_13; person id: 1
processing Shoplifting007_x264_20; person id: 1
processing Shoplifting007_x264_20; person id: 2
processing Shoplifting007_x264_20; person id: 3
processing Shoplifting007_x264_21; person id: 1
processing Shoplifting007_x264_21; person id: 2
processing Shoplifting007_x264_22; person id: 1
processing Shoplifting007_x264_23; person id: 1
processing Shoplifting007_x264_23; person id: 2
processing Shoplifting007_x264_23; person id: 3
processing Shoplifting007_x264_24; person id: 1
processing Shoplifting007_x264_24; person id: 2
processing Shoplifting007_x264_24; person id: 4
processing Shoplifting007_x264_24; person id: 5
processing Shoplifting007_x264_25; person id: 1
processing Shoplifting007_x264_25; person id: 2
processing Shoplifting007_x264_25; person id: 4
processing Shoplifting007_x264_25; person id: 5
processing Shoplifting007_x264_26; person id: 1
processing Shoplifting007_x264_26; person id: 2
processing Shoplifting007_x264_26; person id: 3
processing Shoplifting007_x264_26; person id: 4
processing Shoplifting007_x264_27; person id: 1
processing Shoplifting007_x264_27; person id: 2
processing Shoplifting007_x264_27; person id: 4
processing Shoplifting007_x264_27; person id: 5
processing Shoplifting007_x264_28; person id: 1
processing Shoplifting007_x264_28; person id: 2
processing Shoplifting007_x264_28; person id: 3
processing Shoplifting007_x264_29; person id: 1
processing Shoplifting007_x264_29; person id: 2
processing Shoplifting007_x264_29; person id: 4
processing Shoplifting007_x264_30; person id: 1
processing Shoplifting007_x264_30; person id: 3
processing Shoplifting007_x264_30; person id: 4
processing Shoplifting007_x264_31; person id: 1
processing Shoplifting007_x264_31; person id: 2
processing Shoplifting007_x264_32; person id: 1
processing Shoplifting007_x264_32; person id: 5
processing Shoplifting007_x264_33; person id: 1
processing Shoplifting007_x264_33; person id: 2
processing Shoplifting007_x264_34; person id: 1
processing Shoplifting007_x264_34; person id: 2
processing Shoplifting007_x264_35; person id: 1
processing Shoplifting007_x264_36; person id: 1
processing Shoplifting007_x264_36; person id: 2
processing Shoplifting007_x264_37; person id: 1
processing Shoplifting007_x264_37; person id: 3
processing Shoplifting007_x264_37; person id: 4
processing Shoplifting007_x264_37; person id: 5
processing Shoplifting007_x264_38; person id: 1
processing Shoplifting007_x264_38; person id: 2
processing Shoplifting007_x264_38; person id: 3
processing Shoplifting007_x264_39; person id: 1
processing Shoplifting007_x264_39; person id: 3
processing Shoplifting007_x264_40; person id: 1
processing Shoplifting007_x264_40; person id: 2
processing Shoplifting007_x264_41; person id: 1
processing Shoplifting007_x264_41; person id: 2
processing Shoplifting007_x264_41; person id: 3
processing Shoplifting007_x264_41; person id: 4
processing Shoplifting007_x264_42; person id: 1
processing Shoplifting007_x264_42; person id: 4
processing Shoplifting007_x264_42; person id: 5
processing Shoplifting008_x264_0; person id: 1
processing Shoplifting008_x264_0; person id: 2
processing Shoplifting008_x264_0; person id: 3
processing Shoplifting008_x264_0; person id: 4
processing Shoplifting008_x264_0; person id: 7
processing Shoplifting008_x264_1; person id: 1
processing Shoplifting008_x264_1; person id: 2
processing Shoplifting008_x264_1; person id: 3
processing Shoplifting008_x264_1; person id: 4
processing Shoplifting008_x264_1; person id: 5
processing Shoplifting008_x264_2; person id: 1
processing Shoplifting008_x264_2; person id: 2
processing Shoplifting008_x264_2; person id: 3
processing Shoplifting008_x264_2; person id: 4
processing Shoplifting008_x264_2; person id: 5
processing Shoplifting008_x264_2; person id: 6
processing Shoplifting008_x264_3; person id: 1
processing Shoplifting008_x264_3; person id: 2
processing Shoplifting008_x264_3; person id: 3
processing Shoplifting008_x264_3; person id: 4
processing Shoplifting008_x264_3; person id: 5
processing Shoplifting008_x264_3; person id: 6
processing Shoplifting008_x264_3; person id: 7
processing Shoplifting008_x264_4; person id: 1
processing Shoplifting008_x264_4; person id: 2
processing Shoplifting008_x264_4; person id: 3
processing Shoplifting008_x264_4; person id: 5
processing Shoplifting008_x264_4; person id: 7
processing Shoplifting008_x264_4; person id: 9
processing Shoplifting008_x264_5; person id: 1
processing Shoplifting008_x264_5; person id: 2
processing Shoplifting008_x264_5; person id: 5
processing Shoplifting008_x264_5; person id: 6
processing Shoplifting008_x264_5; person id: 8
processing Shoplifting008_x264_6; person id: 1
processing Shoplifting008_x264_6; person id: 2
processing Shoplifting008_x264_6; person id: 3
processing Shoplifting008_x264_6; person id: 4
processing Shoplifting008_x264_6; person id: 5
processing Shoplifting008_x264_7; person id: 1
processing Shoplifting008_x264_7; person id: 2
processing Shoplifting008_x264_7; person id: 3
processing Shoplifting008_x264_7; person id: 4
processing Shoplifting008_x264_7; person id: 5
processing Shoplifting008_x264_7; person id: 6
processing Shoplifting008_x264_8; person id: 1
processing Shoplifting008_x264_8; person id: 2
processing Shoplifting008_x264_8; person id: 3
processing Shoplifting008_x264_8; person id: 4
processing Shoplifting008_x264_8; person id: 5
processing Shoplifting008_x264_9; person id: 1
processing Shoplifting008_x264_9; person id: 2
processing Shoplifting008_x264_9; person id: 3
processing Shoplifting008_x264_9; person id: 4
processing Shoplifting008_x264_9; person id: 5
processing Shoplifting008_x264_10; person id: 1

,clip,parent,id,features,target
0,Shoplifting001_x264_10,Shoplifting001_x264.mp4,1,"[0.0, 0.0, -3.6674314484295922, -3.86284365242...",1.0
1,Shoplifting001_x264_10,Shoplifting001_x264.mp4,2,"[0.0, 0.0, -4.92564021544842, -3.3099893501284...",1.0
2,Shoplifting001_x264_11,Shoplifting001_x264.mp4,1,"[0.0, 0.0, -5.068451145658348, -3.374883022677...",1.0
3,Shoplifting001_x264_11,Shoplifting001_x264.mp4,5,"[0.0, 0.0, -1.5864730109297471, -1.27144951956...",1.0
4,Shoplifting001_x264_12,Shoplifting001_x264.mp4,1,"[0.0, 0.0, -5.148482308764561, -3.334219974371...",1.0

In [ ]:
df = pd.read_csv(f"{output_path}/features_eyes.csv")
df["features"] = df["features"].map(json.loads)
print(df["target"].value_counts())
print(len(df.iloc[0]["features"]))
df.head()

target
0.0    5120
1.0     335
Name: count, dtype: int64
7178

,clip,parent,id,features,target
0,Shoplifting001_x264_10,Shoplifting001_x264.mp4,1,"[0.0, 0.0, -3.6674314484295922, -3.86284365242...",1.0
1,Shoplifting001_x264_10,Shoplifting001_x264.mp4,2,"[0.0, 0.0, -4.92564021544842, -3.3099893501284...",1.0
2,Shoplifting001_x264_11,Shoplifting001_x264.mp4,1,"[0.0, 0.0, -5.068451145658348, -3.374883022677...",1.0
3,Shoplifting001_x264_11,Shoplifting001_x264.mp4,5,"[0.0, 0.0, -1.5864730109297471, -1.27144951956...",1.0
4,Shoplifting001_x264_12,Shoplifting001_x264.mp4,1,"[0.0, 0.0, -5.148482308764561, -3.334219974371...",1.0

In [ ]:
type(df.iloc[0]["features"]), type(df.iloc[0]["features"][0]), len(df.iloc[0]["features"])

(list, float, 7178)

# Augmentation

In [ ]:
import matplotlib.pyplot as plt

# # High-contrast color palette
# CONTRAST_COLORS = [
#     (0, 128, 255),   # Vivid Blue
#     (255, 128, 0),   # Deep Orange
#     (0, 255, 128),   # Bright Green
#     (255, 0, 128),   # Vivid Pink
#     (128, 0, 255),   # Strong Purple
#     (0, 255, 255),   # Cyan
#     (255, 255, 0),   # Yellow
# ]

# color_palette = sv.ColorPalette(CONTRAST_COLORS)
# Define high-contrast colors using hex values
HEX_COLORS = ['#3ab63f', '#459af5', '#ff5733', '#ffcc00', '#9900cc', '#00cccc', '#ff3399']
# joint_indices_required = {'Neck': 0, 'L_Eye': 1, 'R_Eye': 2, 'L_Shoulder': 3, 'R_Shoulder': 4, 'L_Elbow': 5, 'R_Elbow': 6, 'L_Wrist': 7, 'R_Wrist': 8, 'L_Hip': 9, 'R_Hip': 10}

COLORS = [
    "#FA2597",
    "#00FF00", "#FF1493", "#00FF00", "#FF1493",
    "#00FF00", "#FF1493", "#00FF00", "#FFD700",
    "#00BFFF", "#FFD700"
]

COLORS = [sv.Color.from_hex(color_hex=c) for c in COLORS]

# Create a color palette
color_palette = sv.ColorPalette.from_hex(HEX_COLORS)

def get_contrast_color(person_id):
    """Assigns a high-contrast color to a person ID."""
    return HEX_COLORS[person_id % len(HEX_COLORS)]  # Cycle through colors

def draw_annotated_frame(frame, bounding_box, keypoints):
    #draws a person onto a specific frame
    keypoints, _ = keypoints_to_list(keypoints)
    keypoints = convert_keypoints(keypoints, frame, to_pixel=True)
    keypoints = get_required(keypoints)
    labels = list(joint_indices_required.keys())
    frame_height, frame_width, _ = frame.shape
    person_boxes = []
    keypoint_list = []
    keypoint_labels = []

    # Convert bounding box from relative to absolute values
    x_center, y_center, width, height = bounding_box
    x_min = int((x_center - width / 2) * frame_width)
    y_min = int((y_center - height / 2) * frame_height)
    x_max = int((x_center + width / 2) * frame_width)
    y_max = int((y_center + height / 2) * frame_height)

    person_boxes.append([x_min, y_min, x_max, y_max])
    print(person_boxes)

    keypoint_list.append(keypoints)
    keypoint_labels.append(labels)

    # Convert to numpy array
    person_boxes = np.array(person_boxes)
    keypoints_np = np.array(keypoint_list)

    SKELETON = [
      [0, 1], [0, 2], [0, 3], [0, 4], [0, 9], [0, 10],
      [3, 5], [4, 6], [5, 7], [6, 8],
    ]
    # Create Supervision objects
    detections = sv.Detections(xyxy=person_boxes)
    keypoints = sv.KeyPoints(xy=keypoints_np)

    # Assign unique colors to each person_id
    box_annotator = sv.BoxAnnotator(
        color=sv.Color.BLUE,
        color_lookup = sv.ColorLookup.INDEX,
        thickness=1
    )

    edge_annotator = sv.EdgeAnnotator(color=sv.Color.GREEN, thickness=1, edges=SKELETON)
    vertex_label_annotator = sv.VertexLabelAnnotator(color=COLORS, text_color=sv.Color.BLACK, text_padding=1, border_radius=5)

    # Annotate the frame
    annotated_frame = box_annotator.annotate(scene=frame, detections=detections)
    annotated_frame = edge_annotator.annotate(scene=annotated_frame, key_points=keypoints)
    annotated_frame = vertex_label_annotator.annotate(scene=annotated_frame, key_points=keypoints) #, labels=keypoint_labels

    return annotated_frame


def plot_frame(frame):
  plt.figure(figsize=(10, 5))
  plt.imshow(frame)
  plt.show()

In [ ]:
import albumentations as A
import numpy as np
import cv2

def keypoints_to_list(keypoints, scale=True):
  keypoint_list = []
  labels = []
  for i in range(len(keypoints)):
    coords = [keypoints[i]["x"], keypoints[i]["y"]]
    keypoint_list.append(coords)
    labels.append(keypoints[i]["name"])
  return keypoint_list, labels

def convert_keypoints(keypoints, img, to_pixel=True):
  """converts a list of keypoint pairs from normalized coordinates to and from pixel coordinates"""
  height, width, _ = img.shape
  for keypoint in keypoints:
    keypoint[0] = keypoint[0] * width if to_pixel else keypoint[0] / width
    keypoint[1] = keypoint[1] * height if to_pixel else keypoint[1] / height
  return keypoints

def augment_frame(frame_path, person, transform, flip):
  #person parameter is the values of person at particular frame
  # cap = cv2.VideoCapture(clip_address)
  # cap.set(cv2.CAP_PROP_POS_FRAMES, frame_ind)
  # _, img = cap.read()
  # cap.release()
  img = cv2.imread(frame_path)
  keypoints, labels = keypoints_to_list(person["keypoints"])
  keypoints = convert_keypoints(keypoints, img, to_pixel=True)
  bounding_box = person["bbox"]

  pipeline = A.Compose([transform], bbox_params=A.BboxParams(format="yolo", clip=True, label_fields=["box_label"]), keypoint_params=A.KeypointParams(format="xy", remove_invisible=False))
  transformed_data = pipeline(image=img, keypoints=keypoints, bboxes=[bounding_box], box_label=[person["person_id"]])
  transformed_image = transformed_data["image"]
  height, width, _ = transformed_image.shape
  transformed_keypoints = transformed_data["keypoints"]
  transformed_box = transformed_data["bboxes"][0] if transformed_data["bboxes"] else [0] * 4

  #zero out invalid keypoints
  for i in range(len(transformed_keypoints)):
    if keypoints[i] == [0, 0] or transformed_keypoints[i][0] < 0 or transformed_keypoints[i][0] >= width or transformed_keypoints[i][1] < 0 or transformed_keypoints[i][1] >= height:
      transformed_keypoints[i] = [0, 0]

  #swap left and right keypoints if transform uses flip
  if flip:
    for i, joint in enumerate(labels) :
      if joint.startswith("L_"):
        transformed_keypoints[i], transformed_keypoints[i + 1] = transformed_keypoints[i + 1], transformed_keypoints[i]

  keypoints = convert_keypoints(keypoints, img, to_pixel=False)
  transformed_keypoints = convert_keypoints(transformed_keypoints, transformed_image, to_pixel=False)

  return transformed_box, transformed_keypoints, transformed_image

In [ ]:
from sklearn.model_selection import train_test_split
# load dataset
df = pd.read_csv(f"{output_path}/ids.csv")
counts = df["Has Required"].map(lambda s: len(json.loads(s)))
shoplifting = df["Label"] == 1
df = df[shoplifting]
print(f"dataframe shape: {df.shape}")

#TODO: Make it so only shoplifting samples in training set are augmented

dataframe shape: (340, 5)

In [ ]:
transforms = [A.HorizontalFlip(p=1.0), A.SafeRotate(p=1.0, limit=(-35, 35)), A.Compose([A.HorizontalFlip(p=1.0), A.SafeRotate(p=1.0, limit=(-35, 35))]), A.Perspective(p=1.0), A.Compose([A.HorizontalFlip(p=1.0), A.Perspective(p=1.0)])]
flip = [True, False, True, False, True] #indicates whether the ith transform uses horizontal flip

np.random.seed(42)
random.seed(42)

#df should only have shoplifting samples
for i in range(len(df)):
  row = df.iloc[i]
  parent = row["Parent Video"]
  clip = row["Clip"]
  id = row["ID"]
  # good_frames = json.loads(row["Has Required"])
  print(f"Processing {i + 1} of {len(df)}: {clip}: Person {id}")

  for t, transform in enumerate(transforms):
    # print(f"transform {i}")
    #loaded json should include the neck keypoints
    with open(f"{yolo_path}/{parent}/{clip}/persons/person_{id}/keypoints_0.json") as f:
      person = json.load(f)

    for frame in person:
      # if frame[frame.find('_')+1:] not in good_frames:
      #   continue
      frame_path = f"{yolo_path}/{parent}/{clip}/frames/{frame}.jpg"

      # print("Original")
      # plot_frame(draw_annotated_frame(cv2.imread(frame_path), person[frame][0]["bbox"], person[frame][0]["keypoints"]))

      transformed_box, transformed_keypoints, transformed_image = augment_frame(frame_path, person[frame][0], transform, flip[t])
      person[frame][0]["bbox"] = transformed_box
      for k in range(len(transformed_keypoints)):
        person[frame][0]["keypoints"][k]["x"] = transformed_keypoints[k][0]
        person[frame][0]["keypoints"][k]["y"] = transformed_keypoints[k][1]

      # print("Augmented")
      # plot_frame(draw_annotated_frame(transformed_image, person[frame][0]["bbox"], person[frame][0]["keypoints"]))

    with open(f"{yolo_path}/{parent}/{clip}/persons/person_{id}/keypoints_{t + 1}.json", 'w') as f:
      json.dump(person, f)

Processing 1 of 340: Shoplifting001_x264_10: Person 1
Processing 2 of 340: Shoplifting001_x264_10: Person 2
Processing 3 of 340: Shoplifting001_x264_11: Person 1
Processing 4 of 340: Shoplifting001_x264_11: Person 5
Processing 5 of 340: Shoplifting001_x264_12: Person 1
Processing 6 of 340: Shoplifting001_x264_12: Person 2
Processing 7 of 340: Shoplifting001_x264_13: Person 1
Processing 8 of 340: Shoplifting001_x264_13: Person 3
Processing 9 of 340: Shoplifting001_x264_14: Person 1
Processing 10 of 340: Shoplifting001_x264_14: Person 3
Processing 11 of 340: Shoplifting001_x264_15: Person 1
Processing 12 of 340: Shoplifting001_x264_15: Person 2
Processing 13 of 340: Shoplifting001_x264_16: Person 1
Processing 14 of 340: Shoplifting001_x264_16: Person 2
Processing 15 of 340: Shoplifting003_x264_62: Person 2
Processing 16 of 340: Shoplifting003_x264_63: Person 4
Processing 17 of 340: Shoplifting004_x264_38: Person 2
Processing 18 of 340: Shoplifting004_x264_38: Person 8
Processing 19 of 340: Shoplifting004_x264_39: Person 2
Processing 20 of 340: Shoplifting004_x264_40: Person 1
Processing 21 of 340: Shoplifting004_x264_41: Person 3
Processing 22 of 340: Shoplifting005_x264_6: Person 1
Processing 23 of 340: Shoplifting005_x264_6: Person 2
Processing 24 of 340: Shoplifting005_x264_7: Person 1
Processing 25 of 340: Shoplifting005_x264_7: Person 2
Processing 26 of 340: Shoplifting006_x264_10: Person 2
Processing 27 of 340: Shoplifting006_x264_11: Person 1
Processing 28 of 340: Shoplifting006_x264_12: Person 5
Processing 29 of 340: Shoplifting006_x264_13: Person 1
Processing 30 of 340: Shoplifting006_x264_14: Person 1
Processing 31 of 340: Shoplifting007_x264_4: Person 1
Processing 32 of 340: Shoplifting007_x264_5: Person 1
Processing 33 of 340: Shoplifting007_x264_6: Person 1
Processing 34 of 340: Shoplifting007_x264_6: Person 2
Processing 35 of 340: Shoplifting007_x264_7: Person 3
Processing 36 of 340: Shoplifting007_x264_7: Person 6
Processing 37 of 340: Shoplifting008_x264_44: Person 4
Processing 38 of 340: Shoplifting008_x264_45: Person 3
Processing 39 of 340: Shoplifting009_x264_36: Person 1
Processing 40 of 340: Shoplifting009_x264_37: Person 1
Processing 41 of 340: Shoplifting009_x264_38: Person 1
Processing 42 of 340: Shoplifting009_x264_39: Person 3
Processing 43 of 340: Shoplifting009_x264_40: Person 2
Processing 44 of 340: Shoplifting009_x264_41: Person 1
Processing 45 of 340: Shoplifting009_x264_42: Person 1
Processing 46 of 340: Shoplifting010_x264_5: Person 1
Processing 47 of 340: Shoplifting010_x264_6: Person 1
Processing 48 of 340: Shoplifting010_x264_7: Person 1
Processing 49 of 340: Shoplifting010_x264_8: Person 1
Processing 50 of 340: Shoplifting012_x264_66: Person 1
Processing 51 of 340: Shoplifting012_x264_67: Person 1
Processing 52 of 340: Shoplifting012_x264_68: Person 1
Processing 53 of 340: Shoplifting012_x264_88: Person 1
Processing 54 of 340: Shoplifting012_x264_89: Person 1
Processing 55 of 340: Shoplifting012_x264_90: Person 1
Processing 56 of 340: Shoplifting012_x264_91: Person 1
Processing 57 of 340: Shoplifting012_x264_92: Person 1
Processing 58 of 340: Shoplifting013_x264_7: Person 1
Processing 59 of 340: Shoplifting013_x264_9: Person 1
Processing 60 of 340: Shoplifting013_x264_9: Person 3
Processing 61 of 340: Shoplifting013_x264_10: Person 1
Processing 62 of 340: Shoplifting013_x264_11: Person 1
Processing 63 of 340: Shoplifting013_x264_11: Person 2
Processing 64 of 340: Shoplifting013_x264_12: Person 1
Processing 65 of 340: Shoplifting013_x264_12: Person 2
Processing 66 of 340: Shoplifting013_x264_13: Person 1
Processing 67 of 340: Shoplifting013_x264_13: Person 3
Processing 68 of 340: Shoplifting014_x264_178: Person 1
Processing 69 of 340: Shoplifting014_x264_178: Person 4
Processing 70 of 340: Shoplifting014_x264_179: Person 1
Processing 71 of 340: Shoplifting014_x264_179: Person 2
Processing 72 of 340: Shoplifting014_x264_280: Person 1
Processing 73 of 340: Shoplifting014_x264_280: Person 2
Processing 74 of 340: Shoplifting014_x264_281: Person 1
Processing 75 of 340: Shoplifting014_x264_281: Person 5
Processing 76 of 340: Shoplifting014_x264_282: Person 1
Processing 77 of 340: Shoplifting014_x264_282: Person 2
Processing 78 of 340: Shoplifting014_x264_283: Person 1
Processing 79 of 340: Shoplifting014_x264_284: Person 1
Processing 80 of 340: Shoplifting014_x264_284: Person 2
Processing 81 of 340: Shoplifting014_x264_285: Person 1
Processing 82 of 340: Shoplifting014_x264_285: Person 3
Processing 83 of 340: Shoplifting014_x264_414: Person 1
Processing 84 of 340: Shoplifting014_x264_415: Person 1
Processing 85 of 340: Shoplifting014_x264_415: Person 3
Processing 86 of 340: Shoplifting014_x264_416: Person 2
Processing 87 of 340: Shoplifting014_x264_416: Person 3
Processing 88 of 340: Shoplifting014_x264_419: Person 1
Processing 89 of 340: Shoplifting014_x264_419: Person 2
Processing 90 of 340: Shoplifting014_x264_420: Person 2
Processing 91 of 340: Shoplifting014_x264_420: Person 4
Processing 92 of 340: Shoplifting014_x264_421: Person 1
Processing 93 of 340: Shoplifting014_x264_421: Person 6
Processing 94 of 340: Shoplifting014_x264_422: Person 1
Processing 95 of 340: Shoplifting014_x264_422: Person 4
Processing 96 of 340: Shoplifting014_x264_450: Person 1
Processing 97 of 340: Shoplifting014_x264_451: Person 2
Processing 98 of 340: Shoplifting014_x264_452: Person 2
Processing 99 of 340: Shoplifting014_x264_453: Person 1
Processing 100 of 340: Shoplifting014_x264_454: Person 1
Processing 101 of 340: Shoplifting014_x264_455: Person 1
Processing 102 of 340: Shoplifting014_x264_456: Person 1
Processing 103 of 340: Shoplifting015_x264_16: Person 1
Processing 104 of 340: Shoplifting015_x264_17: Person 1
Processing 105 of 340: Shoplifting016_x264_4: Person 1
Processing 106 of 340: Shoplifting016_x264_5: Person 1
Processing 107 of 340: Shoplifting016_x264_6: Person 1
Processing 108 of 340: Shoplifting017_x264_2: Person 1
Processing 109 of 340: Shoplifting017_x264_3: Person 1
Processing 110 of 340: Shoplifting018_x264_7: Person 2
Processing 111 of 340: Shoplifting019_x264_2: Person 1
Processing 112 of 340: Shoplifting019_x264_2: Person 2
Processing 113 of 340: Shoplifting019_x264_2: Person 5
Processing 114 of 340: Shoplifting019_x264_3: Person 1
Processing 115 of 340: Shoplifting019_x264_3: Person 3
Processing 116 of 340: Shoplifting020_x264_18: Person 1
Processing 117 of 340: Shoplifting020_x264_20: Person 1
Processing 118 of 340: Shoplifting020_x264_20: Person 2
Processing 119 of 340: Shoplifting021_x264_17: Person 2
Processing 120 of 340: Shoplifting021_x264_18: Person 2
Processing 121 of 340: Shoplifting022_x264_2: Person 1
Processing 122 of 340: Shoplifting022_x264_3: Person 2
Processing 123 of 340: Shoplifting022_x264_5: Person 2
Processing 124 of 340: Shoplifting022_x264_7: Person 1
Processing 125 of 340: Shoplifting022_x264_8: Person 1
Processing 126 of 340: Shoplifting022_x264_11: Person 2
Processing 127 of 340: Shoplifting022_x264_12: Person 2
Processing 128 of 340: Shoplifting022_x264_15: Person 1
Processing 129 of 340: Shoplifting022_x264_16: Person 1
Processing 130 of 340: Shoplifting024_x264_6: Person 1
Processing 131 of 340: Shoplifting024_x264_7: Person 1
Processing 132 of 340: Shoplifting024_x264_8: Person 1
Processing 133 of 340: Shoplifting025_x264_3: Person 1
Processing 134 of 340: Shoplifting025_x264_5: Person 2
Processing 135 of 340: Shoplifting025_x264_6: Person 1
Processing 136 of 340: Shoplifting026_x264_1: Person 1
Processing 137 of 340: Shoplifting026_x264_2: Person 1
Processing 138 of 340: Shoplifting026_x264_10: Person 3
Processing 139 of 340: Shoplifting027_x264_8: Person 1
Processing 140 of 340: Shoplifting027_x264_9: Person 1
Processing 141 of 340: Shoplifting028_x264_4: Person 2
Processing 142 of 340: Shoplifting028_x264_5: Person 1
Processing 143 of 340: Shoplifting028_x264_6: Person 2
Processing 144 of 340: Shoplifting028_x264_7: Person 1
Processing 145 of 340: Shoplifting028_x264_7: Person 2
Processing 146 of 340: Shoplifting028_x264_8: Person 1
Processing 147 of 340: Shoplifting029_x264_9: Person 1
Processing 148 of 340: Shoplifting029_x264_9: Person 2
Processing 149 of 340: Shoplifting029_x264_10: Person 1
Processing 150 of 340: Shoplifting029_x264_10: Person 2
Processing 151 of 340: Shoplifting029_x264_11: Person 1
Processing 152 of 340: Shoplifting029_x264_11: Person 2
Processing 153 of 340: Shoplifting029_x264_12: Person 1
Processing 154 of 340: Shoplifting029_x264_12: Person 2
Processing 155 of 340: Shoplifting030_x264_135: Person 1
Processing 156 of 340: Shoplifting030_x264_136: Person 3
Processing 157 of 340: Shoplifting030_x264_137: Person 1
Processing 158 of 340: Shoplifting030_x264_139: Person 1
Processing 159 of 340: Shoplifting031_x264_1: Person 2
Processing 160 of 340: Shoplifting031_x264_2: Person 1
Processing 161 of 340: Shoplifting031_x264_3: Person 1
Processing 162 of 340: Shoplifting032_x264_8: Person 1
Processing 163 of 340: Shoplifting033_x264_5: Person 1
Processing 164 of 340: Shoplifting033_x264_6: Person 1
Processing 165 of 340: Shoplifting034_x264_38: Person 1
Processing 166 of 340: Shoplifting034_x264_39: Person 1
Processing 167 of 340: Shoplifting034_x264_42: Person 1
Processing 168 of 340: Shoplifting034_x264_42: Person 2
Processing 169 of 340: Shoplifting034_x264_43: Person 1
Processing 170 of 340: Shoplifting034_x264_46: Person 1
Processing 171 of 340: Shoplifting034_x264_47: Person 1
Processing 172 of 340: Shoplifting034_x264_60: Person 1
Processing 173 of 340: Shoplifting034_x264_60: Person 2
Processing 174 of 340: Shoplifting034_x264_61: Person 1
Processing 175 of 340: Shoplifting034_x264_61: Person 2
Processing 176 of 340: Shoplifting034_x264_67: Person 1
Processing 177 of 340: Shoplifting034_x264_67: Person 2
Processing 178 of 340: Shoplifting034_x264_69: Person 1
Processing 179 of 340: Shoplifting034_x264_69: Person 2
Processing 180 of 340: Shoplifting036_x264_25: Person 1
Processing 181 of 340: Shoplifting036_x264_25: Person 2
Processing 182 of 340: Shoplifting036_x264_26: Person 1
Processing 183 of 340: Shoplifting036_x264_26: Person 2
Processing 184 of 340: Shoplifting036_x264_27: Person 1
Processing 185 of 340: Shoplifting036_x264_27: Person 3
Processing 186 of 340: Shoplifting036_x264_27: Person 4
Processing 187 of 340: Shoplifting036_x264_28: Person 1
Processing 188 of 340: Shoplifting036_x264_28: Person 3
Processing 189 of 340: Shoplifting036_x264_28: Person 4
Processing 190 of 340: Shoplifting037_x264_8: Person 1
Processing 191 of 340: Shoplifting037_x264_9: Person 1
Processing 192 of 340: Shoplifting038_x264_12: Person 1
Processing 193 of 340: Shoplifting038_x264_20: Person 1
Processing 194 of 340: Shoplifting039_x264_17: Person 2
Processing 195 of 340: Shoplifting039_x264_18: Person 1
Processing 196 of 340: Shoplifting040_x264_15: Person 1
Processing 197 of 340: Shoplifting040_x264_15: Person 2
Processing 198 of 340: Shoplifting040_x264_16: Person 1
Processing 199 of 340: Shoplifting040_x264_16: Person 2
Processing 200 of 340: Shoplifting040_x264_37: Person 1
Processing 201 of 340: Shoplifting040_x264_37: Person 3
Processing 202 of 340: Shoplifting040_x264_38: Person 1
Processing 203 of 340: Shoplifting040_x264_38: Person 3
Processing 204 of 340: Shoplifting040_x264_39: Person 1
Processing 205 of 340: Shoplifting040_x264_39: Person 2
Processing 206 of 340: Shoplifting040_x264_70: Person 1
Processing 207 of 340: Shoplifting040_x264_70: Person 3
Processing 208 of 340: Shoplifting040_x264_71: Person 1
Processing 209 of 340: Shoplifting040_x264_71: Person 2
Processing 210 of 340: Shoplifting040_x264_84: Person 1
Processing 211 of 340: Shoplifting040_x264_84: Person 2
Processing 212 of 340: Shoplifting040_x264_85: Person 1
Processing 213 of 340: Shoplifting040_x264_85: Person 3
Processing 214 of 340: Shoplifting040_x264_108: Person 1
Processing 215 of 340: Shoplifting040_x264_108: Person 3
Processing 216 of 340: Shoplifting040_x264_109: Person 2
Processing 217 of 340: Shoplifting041_x264_17: Person 2
Processing 218 of 340: Shoplifting041_x264_18: Person 2
Processing 219 of 340: Shoplifting041_x264_56: Person 1
Processing 220 of 340: Shoplifting041_x264_57: Person 1
Processing 221 of 340: Shoplifting041_x264_58: Person 1
Processing 222 of 340: Shoplifting041_x264_59: Person 1
Processing 223 of 340: Shoplifting041_x264_60: Person 1
Processing 224 of 340: Shoplifting041_x264_76: Person 1
Processing 225 of 340: Shoplifting041_x264_77: Person 1
Processing 226 of 340: Shoplifting042_x264_15: Person 4
Processing 227 of 340: Shoplifting042_x264_16: Person 4
Processing 228 of 340: Shoplifting042_x264_17: Person 3
Processing 229 of 340: Shoplifting042_x264_18: Person 3
Processing 230 of 340: Shoplifting042_x264_19: Person 4
Processing 231 of 340: Shoplifting042_x264_20: Person 3
Processing 232 of 340: Shoplifting042_x264_20: Person 8
Processing 233 of 340: Shoplifting042_x264_21: Person 2
Processing 234 of 340: Shoplifting042_x264_21: Person 3
Processing 235 of 340: Shoplifting042_x264_22: Person 1
Processing 236 of 340: Shoplifting042_x264_22: Person 3
Processing 237 of 340: Shoplifting042_x264_23: Person 2
Processing 238 of 340: Shoplifting042_x264_23: Person 4
Processing 239 of 340: Shoplifting042_x264_24: Person 1
Processing 240 of 340: Shoplifting042_x264_24: Person 4
Processing 241 of 340: Shoplifting042_x264_24: Person 8
Processing 242 of 340: Shoplifting043_x264_49: Person 1
Processing 243 of 340: Shoplifting043_x264_49: Person 3
Processing 244 of 340: Shoplifting043_x264_51: Person 1
Processing 245 of 340: Shoplifting043_x264_57: Person 1
Processing 246 of 340: Shoplifting044_x264_86: Person 1
Processing 247 of 340: Shoplifting044_x264_87: Person 2
Processing 248 of 340: Shoplifting044_x264_88: Person 4
Processing 249 of 340: Shoplifting044_x264_89: Person 2
Processing 250 of 340: Shoplifting044_x264_90: Person 2
Processing 251 of 340: Shoplifting044_x264_91: Person 2
Processing 252 of 340: Shoplifting044_x264_92: Person 3
Processing 253 of 340: Shoplifting044_x264_93: Person 2
Processing 254 of 340: Shoplifting044_x264_94: Person 2
Processing 255 of 340: Shoplifting044_x264_95: Person 2
Processing 256 of 340: Shoplifting044_x264_96: Person 2
Processing 257 of 340: Shoplifting045_x264_6: Person 4
Processing 258 of 340: Shoplifting045_x264_6: Person 5
Processing 259 of 340: Shoplifting045_x264_6: Person 6
Processing 260 of 340: Shoplifting045_x264_7: Person 1
Processing 261 of 340: Shoplifting045_x264_7: Person 2
Processing 262 of 340: Shoplifting045_x264_7: Person 4
Processing 263 of 340: Shoplifting045_x264_7: Person 5
Processing 264 of 340: Shoplifting045_x264_8: Person 2
Processing 265 of 340: Shoplifting045_x264_8: Person 5
Processing 266 of 340: Shoplifting045_x264_8: Person 6
Processing 267 of 340: Shoplifting045_x264_9: Person 2
Processing 268 of 340: Shoplifting045_x264_9: Person 3
Processing 269 of 340: Shoplifting045_x264_9: Person 4
Processing 270 of 340: Shoplifting045_x264_9: Person 5
Processing 271 of 340: Shoplifting045_x264_9: Person 6
Processing 272 of 340: Shoplifting045_x264_10: Person 1
Processing 273 of 340: Shoplifting045_x264_10: Person 2
Processing 274 of 340: Shoplifting045_x264_10: Person 4
Processing 275 of 340: Shoplifting045_x264_12: Person 1
Processing 276 of 340: Shoplifting047_x264_9: Person 1
Processing 277 of 340: Shoplifting047_x264_9: Person 2
Processing 278 of 340: Shoplifting047_x264_9: Person 4
Processing 279 of 340: Shoplifting047_x264_10: Person 1
Processing 280 of 340: Shoplifting047_x264_10: Person 2
Processing 281 of 340: Shoplifting047_x264_10: Person 3
Processing 282 of 340: Shoplifting047_x264_11: Person 1
Processing 283 of 340: Shoplifting047_x264_11: Person 2
Processing 284 of 340: Shoplifting047_x264_11: Person 5
Processing 285 of 340: Shoplifting047_x264_13: Person 2
Processing 286 of 340: Shoplifting047_x264_14: Person 2
Processing 287 of 340: Shoplifting047_x264_14: Person 3
Processing 288 of 340: Shoplifting047_x264_15: Person 1
Processing 289 of 340: Shoplifting047_x264_15: Person 3
Processing 290 of 340: Shoplifting047_x264_16: Person 2
Processing 291 of 340: Shoplifting047_x264_17: Person 1
Processing 292 of 340: Shoplifting047_x264_18: Person 5
Processing 293 of 340: Shoplifting047_x264_19: Person 1
Processing 294 of 340: Shoplifting048_x264_1: Person 1
Processing 295 of 340: Shoplifting048_x264_1: Person 2
Processing 296 of 340: Shoplifting048_x264_1: Person 3
Processing 297 of 340: Shoplifting048_x264_2: Person 1
Processing 298 of 340: Shoplifting048_x264_2: Person 2
Processing 299 of 340: Shoplifting048_x264_2: Person 3
Processing 300 of 340: Shoplifting048_x264_7: Person 1
Processing 301 of 340: Shoplifting048_x264_7: Person 2
Processing 302 of 340: Shoplifting048_x264_7: Person 3
Processing 303 of 340: Shoplifting048_x264_8: Person 1
Processing 304 of 340: Shoplifting048_x264_9: Person 1
Processing 305 of 340: Shoplifting048_x264_9: Person 2
Processing 306 of 340: Shoplifting048_x264_9: Person 3
Processing 307 of 340: Shoplifting049_x264_8: Person 1
Processing 308 of 340: Shoplifting049_x264_9: Person 1
Processing 309 of 340: Shoplifting049_x264_10: Person 1
Processing 310 of 340: Shoplifting049_x264_11: Person 1
Processing 311 of 340: Shoplifting051_x264_38: Person 3
Processing 312 of 340: Shoplifting051_x264_39: Person 3
Processing 313 of 340: Shoplifting051_x264_40: Person 3
Processing 314 of 340: Shoplifting051_x264_41: Person 4
Processing 315 of 340: Shoplifting051_x264_42: Person 3
Processing 316 of 340: Shoplifting051_x264_43: Person 3
Processing 317 of 340: Shoplifting052_x264_6: Person 1
Processing 318 of 340: Shoplifting052_x264_7: Person 1
Processing 319 of 340: Shoplifting052_x264_8: Person 1
Processing 320 of 340: Shoplifting052_x264_13: Person 1
Processing 321 of 340: Shoplifting052_x264_14: Person 1
Processing 322 of 340: Shoplifting052_x264_15: Person 1
Processing 323 of 340: Shoplifting052_x264_22: Person 1
Processing 324 of 340: Shoplifting052_x264_23: Person 1
Processing 325 of 340: Shoplifting052_x264_32: Person 1
Processing 326 of 340: Shoplifting052_x264_33: Person 1
Processing 327 of 340: Shoplifting052_x264_39: Person 1
Processing 328 of 340: Shoplifting052_x264_40: Person 1
Processing 329 of 340: Shoplifting052_x264_41: Person 1
Processing 330 of 340: Shoplifting053_x264_10: Person 1
Processing 331 of 340: Shoplifting053_x264_11: Person 1
Processing 332 of 340: Shoplifting053_x264_12: Person 1
Processing 333 of 340: Shoplifting053_x264_13: Person 1
Processing 334 of 340: Shoplifting054_x264_4: Person 1
Processing 335 of 340: Shoplifting054_x264_5: Person 1
Processing 336 of 340: Shoplifting054_x264_6: Person 1
Processing 337 of 340: Shoplifting055_x264_17: Person 1
Processing 338 of 340: Shoplifting055_x264_18: Person 1
Processing 339 of 340: Shoplifting055_x264_19: Person 1
Processing 340 of 340: Shoplifting055_x264_20: Person 1

In [ ]:
#make csv for augmented dataset

ids_df = pd.read_csv(f"{output_path}/ids.csv")
indexes = pd.DataFrame({"Label": [0] + [1] * (len(transforms) + 1), "Index": [0] + list(range(len(transforms) + 1))})
augmented_df = ids_df.merge(indexes, on="Label")
drop_rows = []
for i in range(len(augmented_df)):
  row = augmented_df.iloc[i]
  clip = row["Clip"]
  parent = row["Parent Video"]
  id = row["ID"]
  index = row["Index"]
  print(f"Processing {i + 1} of {len(augmented_df)}: {clip}: Person {id} {index}")
  if not os.path.exists(f"{yolo_path}/{parent}/{clip}/persons/person_{id}/keypoints_{index}.json"):
    drop_rows.append(i)
    continue
augmented_df = augmented_df.drop(drop_rows)
print(len(augmented_df), augmented_df["Label"].value_counts())
augmented_df.to_csv(f"{output_path}/augmented_ids.csv", index=False)

Streaming output truncated to the last 5000 lines.
Processing 2263 of 7258: Shoplifting003_x264_82: Person 2 0
Processing 2264 of 7258: Shoplifting003_x264_83: Person 1 0
Processing 2265 of 7258: Shoplifting003_x264_83: Person 2 0
Processing 2266 of 7258: Shoplifting003_x264_84: Person 1 0
Processing 2267 of 7258: Shoplifting003_x264_86: Person 1 0
Processing 2268 of 7258: Shoplifting003_x264_86: Person 2 0
Processing 2269 of 7258: Shoplifting003_x264_87: Person 1 0
Processing 2270 of 7258: Shoplifting003_x264_87: Person 2 0
Processing 2271 of 7258: Shoplifting003_x264_87: Person 3 0
Processing 2272 of 7258: Shoplifting003_x264_88: Person 1 0
Processing 2273 of 7258: Shoplifting003_x264_89: Person 1 0
Processing 2274 of 7258: Shoplifting004_x264_0: Person 1 0
Processing 2275 of 7258: Shoplifting004_x264_0: Person 2 0
Processing 2276 of 7258: Shoplifting004_x264_0: Person 3 0
Processing 2277 of 7258: Shoplifting004_x264_1: Person 1 0
Processing 2278 of 7258: Shoplifting004_x264_1: Person 2 0
Processing 2279 of 7258: Shoplifting004_x264_2: Person 1 0
Processing 2280 of 7258: Shoplifting004_x264_2: Person 2 0
Processing 2281 of 7258: Shoplifting004_x264_2: Person 3 0
Processing 2282 of 7258: Shoplifting004_x264_3: Person 1 0
Processing 2283 of 7258: Shoplifting004_x264_3: Person 2 0
Processing 2284 of 7258: Shoplifting004_x264_4: Person 1 0
Processing 2285 of 7258: Shoplifting004_x264_4: Person 2 0
Processing 2286 of 7258: Shoplifting004_x264_4: Person 3 0
Processing 2287 of 7258: Shoplifting004_x264_4: Person 4 0
Processing 2288 of 7258: Shoplifting004_x264_5: Person 1 0
Processing 2289 of 7258: Shoplifting004_x264_5: Person 2 0
Processing 2290 of 7258: Shoplifting004_x264_5: Person 4 0
Processing 2291 of 7258: Shoplifting004_x264_6: Person 1 0
Processing 2292 of 7258: Shoplifting004_x264_6: Person 2 0
Processing 2293 of 7258: Shoplifting004_x264_6: Person 3 0
Processing 2294 of 7258: Shoplifting004_x264_6: Person 4 0
Processing 2295 of 7258: Shoplifting004_x264_7: Person 1 0
Processing 2296 of 7258: Shoplifting004_x264_7: Person 3 0
Processing 2297 of 7258: Shoplifting004_x264_8: Person 1 0
Processing 2298 of 7258: Shoplifting004_x264_8: Person 2 0
Processing 2299 of 7258: Shoplifting004_x264_8: Person 3 0
Processing 2300 of 7258: Shoplifting004_x264_8: Person 4 0
Processing 2301 of 7258: Shoplifting004_x264_9: Person 1 0
Processing 2302 of 7258: Shoplifting004_x264_9: Person 3 0
Processing 2303 of 7258: Shoplifting004_x264_9: Person 4 0
Processing 2304 of 7258: Shoplifting004_x264_9: Person 5 0
Processing 2305 of 7258: Shoplifting004_x264_9: Person 6 0
Processing 2306 of 7258: Shoplifting004_x264_9: Person 7 0
Processing 2307 of 7258: Shoplifting004_x264_10: Person 1 0
Processing 2308 of 7258: Shoplifting004_x264_10: Person 2 0
Processing 2309 of 7258: Shoplifting004_x264_10: Person 3 0
Processing 2310 of 7258: Shoplifting004_x264_11: Person 1 0
Processing 2311 of 7258: Shoplifting004_x264_11: Person 2 0
Processing 2312 of 7258: Shoplifting004_x264_11: Person 3 0
Processing 2313 of 7258: Shoplifting004_x264_11: Person 4 0
Processing 2314 of 7258: Shoplifting004_x264_11: Person 6 0
Processing 2315 of 7258: Shoplifting004_x264_12: Person 1 0
Processing 2316 of 7258: Shoplifting004_x264_12: Person 2 0
Processing 2317 of 7258: Shoplifting004_x264_12: Person 3 0
Processing 2318 of 7258: Shoplifting004_x264_13: Person 1 0
Processing 2319 of 7258: Shoplifting004_x264_13: Person 2 0
Processing 2320 of 7258: Shoplifting004_x264_13: Person 5 0
Processing 2321 of 7258: Shoplifting004_x264_14: Person 1 0
Processing 2322 of 7258: Shoplifting004_x264_14: Person 3 0
Processing 2323 of 7258: Shoplifting004_x264_14: Person 5 0
Processing 2324 of 7258: Shoplifting004_x264_14: Person 7 0
Processing 2325 of 7258: Shoplifting004_x264_15: Person 1 0
Processing 2326 of 7258: Shoplifting004_x264_15: Person 2 0
Processing 2327 of 7258: Shoplifting004_x264_15: Person 3 0
Processing 2328 of 7258: Shoplifting004_x264_16: Person 1 0
Processing 2329 of 7258: Shoplifting004_x264_16: Person 2 0
Processing 2330 of 7258: Shoplifting004_x264_16: Person 3 0
Processing 2331 of 7258: Shoplifting004_x264_16: Person 6 0
Processing 2332 of 7258: Shoplifting004_x264_17: Person 1 0
Processing 2333 of 7258: Shoplifting004_x264_17: Person 2 0
Processing 2334 of 7258: Shoplifting004_x264_17: Person 3 0
Processing 2335 of 7258: Shoplifting004_x264_17: Person 4 0
Processing 2336 of 7258: Shoplifting004_x264_17: Person 6 0
Processing 2337 of 7258: Shoplifting004_x264_18: Person 1 0
Processing 2338 of 7258: Shoplifting004_x264_18: Person 2 0
Processing 2339 of 7258: Shoplifting004_x264_18: Person 3 0
Processing 2340 of 7258: Shoplifting004_x264_18: Person 4 0
Processing 2341 of 7258: Shoplifting004_x264_19: Person 1 0
Processing 2342 of 7258: Shoplifting004_x264_19: Person 2 0
Processing 2343 of 7258: Shoplifting004_x264_19: Person 3 0
Processing 2344 of 7258: Shoplifting004_x264_19: Person 4 0
Processing 2345 of 7258: Shoplifting004_x264_20: Person 1 0
Processing 2346 of 7258: Shoplifting004_x264_20: Person 2 0
Processing 2347 of 7258: Shoplifting004_x264_20: Person 3 0
Processing 2348 of 7258: Shoplifting004_x264_20: Person 4 0
Processing 2349 of 7258: Shoplifting004_x264_21: Person 1 0
Processing 2350 of 7258: Shoplifting004_x264_21: Person 2 0
Processing 2351 of 7258: Shoplifting004_x264_21: Person 3 0
Processing 2352 of 7258: Shoplifting004_x264_21: Person 4 0
Processing 2353 of 7258: Shoplifting004_x264_22: Person 1 0
Processing 2354 of 7258: Shoplifting004_x264_22: Person 2 0
Processing 2355 of 7258: Shoplifting004_x264_22: Person 3 0
Processing 2356 of 7258: Shoplifting004_x264_22: Person 4 0
Processing 2357 of 7258: Shoplifting004_x264_23: Person 1 0
Processing 2358 of 7258: Shoplifting004_x264_23: Person 2 0
Processing 2359 of 7258: Shoplifting004_x264_23: Person 3 0
Processing 2360 of 7258: Shoplifting004_x264_23: Person 4 0
Processing 2361 of 7258: Shoplifting004_x264_23: Person 5 0
Processing 2362 of 7258: Shoplifting004_x264_24: Person 1 0
Processing 2363 of 7258: Shoplifting004_x264_24: Person 2 0
Processing 2364 of 7258: Shoplifting004_x264_24: Person 3 0
Processing 2365 of 7258: Shoplifting004_x264_24: Person 4 0
Processing 2366 of 7258: Shoplifting004_x264_25: Person 1 0
Processing 2367 of 7258: Shoplifting004_x264_25: Person 2 0
Processing 2368 of 7258: Shoplifting004_x264_25: Person 3 0
Processing 2369 of 7258: Shoplifting004_x264_25: Person 5 0
Processing 2370 of 7258: Shoplifting004_x264_26: Person 1 0
Processing 2371 of 7258: Shoplifting004_x264_26: Person 2 0
Processing 2372 of 7258: Shoplifting004_x264_26: Person 3 0
Processing 2373 of 7258: Shoplifting004_x264_26: Person 4 0
Processing 2374 of 7258: Shoplifting004_x264_26: Person 6 0
Processing 2375 of 7258: Shoplifting004_x264_26: Person 7 0
Processing 2376 of 7258: Shoplifting004_x264_27: Person 1 0
Processing 2377 of 7258: Shoplifting004_x264_27: Person 2 0
Processing 2378 of 7258: Shoplifting004_x264_27: Person 3 0
Processing 2379 of 7258: Shoplifting004_x264_27: Person 6 0
Processing 2380 of 7258: Shoplifting004_x264_27: Person 7 0
Processing 2381 of 7258: Shoplifting004_x264_27: Person 10 0
Processing 2382 of 7258: Shoplifting004_x264_28: Person 1 0
Processing 2383 of 7258: Shoplifting004_x264_28: Person 2 0
Processing 2384 of 7258: Shoplifting004_x264_28: Person 3 0
Processing 2385 of 7258: Shoplifting004_x264_28: Person 4 0
Processing 2386 of 7258: Shoplifting004_x264_28: Person 6 0
Processing 2387 of 7258: Shoplifting004_x264_29: Person 1 0
Processing 2388 of 7258: Shoplifting004_x264_29: Person 2 0
Processing 2389 of 7258: Shoplifting004_x264_29: Person 3 0
Processing 2390 of 7258: Shoplifting004_x264_29: Person 8 0
Processing 2391 of 7258: Shoplifting004_x264_29: Person 9 0
Processing 2392 of 7258: Shoplifting004_x264_30: Person 1 0
Processing 2393 of 7258: Shoplifting004_x264_30: Person 2 0
Processing 2394 of 7258: Shoplifting004_x264_30: Person 3 0
Processing 2395 of 7258: Shoplifting004_x264_30: Person 4 0
Processing 2396 of 7258: Shoplifting004_x264_30: Person 5 0
Processing 2397 of 7258: Shoplifting004_x264_31: Person 1 0
Processing 2398 of 7258: Shoplifting004_x264_31: Person 2 0
Processing 2399 of 7258: Shoplifting004_x264_31: Person 3 0
Processing 2400 of 7258: Shoplifting004_x264_31: Person 4 0
Processing 2401 of 7258: Shoplifting004_x264_32: Person 1 0
Processing 2402 of 7258: Shoplifting004_x264_32: Person 2 0
Processing 2403 of 7258: Shoplifting004_x264_32: Person 3 0
Processing 2404 of 7258: Shoplifting004_x264_32: Person 4 0
Processing 2405 of 7258: Shoplifting004_x264_32: Person 6 0
Processing 2406 of 7258: Shoplifting004_x264_33: Person 1 0
Processing 2407 of 7258: Shoplifting004_x264_33: Person 2 0
Processing 2408 of 7258: Shoplifting004_x264_33: Person 3 0
Processing 2409 of 7258: Shoplifting004_x264_33: Person 4 0
Processing 2410 of 7258: Shoplifting004_x264_34: Person 1 0
Processing 2411 of 7258: Shoplifting004_x264_34: Person 2 0
Processing 2412 of 7258: Shoplifting004_x264_34: Person 3 0
Processing 2413 of 7258: Shoplifting004_x264_34: Person 4 0
Processing 2414 of 7258: Shoplifting004_x264_35: Person 1 0
Processing 2415 of 7258: Shoplifting004_x264_35: Person 2 0
Processing 2416 of 7258: Shoplifting004_x264_35: Person 3 0
Processing 2417 of 7258: Shoplifting004_x264_35: Person 4 0
Processing 2418 of 7258: Shoplifting004_x264_35: Person 5 0
Processing 2419 of 7258: Shoplifting004_x264_36: Person 1 0
Processing 2420 of 7258: Shoplifting004_x264_36: Person 2 0
Processing 2421 of 7258: Shoplifting004_x264_36: Person 3 0
Processing 2422 of 7258: Shoplifting004_x264_36: Person 4 0
Processing 2423 of 7258: Shoplifting004_x264_37: Person 1 0
Processing 2424 of 7258: Shoplifting004_x264_37: Person 2 0
Processing 2425 of 7258: Shoplifting004_x264_37: Person 3 0
Processing 2426 of 7258: Shoplifting004_x264_37: Person 4 0
Processing 2427 of 7258: Shoplifting004_x264_37: Person 5 0
Processing 2428 of 7258: Shoplifting004_x264_42: Person 1 0
Processing 2429 of 7258: Shoplifting004_x264_42: Person 2 0
Processing 2430 of 7258: Shoplifting004_x264_43: Person 1 0
Processing 2431 of 7258: Shoplifting004_x264_43: Person 2 0
Processing 2432 of 7258: Shoplifting004_x264_44: Person 1 0
Processing 2433 of 7258: Shoplifting004_x264_44: Person 2 0
Processing 2434 of 7258: Shoplifting004_x264_44: Person 4 0
Processing 2435 of 7258: Shoplifting004_x264_45: Person 1 0
Processing 2436 of 7258: Shoplifting004_x264_45: Person 2 0
Processing 2437 of 7258: Shoplifting004_x264_46: Person 1 0
Processing 2438 of 7258: Shoplifting004_x264_46: Person 2 0
Processing 2439 of 7258: Shoplifting004_x264_47: Person 1 0
Processing 2440 of 7258: Shoplifting004_x264_47: Person 2 0
Processing 2441 of 7258: Shoplifting004_x264_47: Person 3 0
Processing 2442 of 7258: Shoplifting004_x264_47: Person 4 0
Processing 2443 of 7258: Shoplifting004_x264_48: Person 1 0
Processing 2444 of 7258: Shoplifting004_x264_48: Person 2 0
Processing 2445 of 7258: Shoplifting004_x264_48: Person 3 0
Processing 2446 of 7258: Shoplifting004_x264_48: Person 4 0
Processing 2447 of 7258: Shoplifting004_x264_49: Person 1 0
Processing 2448 of 7258: Shoplifting004_x264_49: Person 2 0
Processing 2449 of 7258: Shoplifting004_x264_49: Person 4 0
Processing 2450 of 7258: Shoplifting004_x264_49: Person 7 0
Processing 2451 of 7258: Shoplifting004_x264_50: Person 1 0
Processing 2452 of 7258: Shoplifting004_x264_50: Person 2 0
Processing 2453 of 7258: Shoplifting004_x264_50: Person 3 0
Processing 2454 of 7258: Shoplifting004_x264_50: Person 4 0
Processing 2455 of 7258: Shoplifting004_x264_51: Person 1 0
Processing 2456 of 7258: Shoplifting004_x264_51: Person 2 0
Processing 2457 of 7258: Shoplifting004_x264_51: Person 3 0
Processing 2458 of 7258: Shoplifting004_x264_52: Person 1 0
Processing 2459 of 7258: Shoplifting004_x264_52: Person 2 0
Processing 2460 of 7258: Shoplifting004_x264_52: Person 4 0
Processing 2461 of 7258: Shoplifting004_x264_53: Person 1 0
Processing 2462 of 7258: Shoplifting004_x264_53: Person 2 0
Processing 2463 of 7258: Shoplifting004_x264_53: Person 5 0
Processing 2464 of 7258: Shoplifting004_x264_54: Person 1 0
Processing 2465 of 7258: Shoplifting004_x264_54: Person 2 0
Processing 2466 of 7258: Shoplifting004_x264_54: Person 4 0
Processing 2467 of 7258: Shoplifting004_x264_54: Person 5 0
Processing 2468 of 7258: Shoplifting004_x264_55: Person 1 0
Processing 2469 of 7258: Shoplifting004_x264_55: Person 2 0
Processing 2470 of 7258: Shoplifting004_x264_55: Person 3 0
Processing 2471 of 7258: Shoplifting004_x264_55: Person 5 0
Processing 2472 of 7258: Shoplifting005_x264_0: Person 1 0
Processing 2473 of 7258: Shoplifting005_x264_1: Person 1 0
Processing 2474 of 7258: Shoplifting005_x264_1: Person 2 0
Processing 2475 of 7258: Shoplifting005_x264_1: Person 3 0
Processing 2476 of 7258: Shoplifting005_x264_2: Person 1 0
Processing 2477 of 7258: Shoplifting005_x264_2: Person 2 0
Processing 2478 of 7258: Shoplifting005_x264_2: Person 3 0
Processing 2479 of 7258: Shoplifting005_x264_3: Person 1 0
Processing 2480 of 7258: Shoplifting005_x264_3: Person 2 0
Processing 2481 of 7258: Shoplifting005_x264_3: Person 3 0
Processing 2482 of 7258: Shoplifting005_x264_4: Person 1 0
Processing 2483 of 7258: Shoplifting005_x264_5: Person 1 0
Processing 2484 of 7258: Shoplifting005_x264_5: Person 2 0
Processing 2485 of 7258: Shoplifting005_x264_8: Person 1 0
Processing 2486 of 7258: Shoplifting005_x264_9: Person 1 0
Processing 2487 of 7258: Shoplifting005_x264_10: Person 1 0
Processing 2488 of 7258: Shoplifting005_x264_11: Person 1 0
Processing 2489 of 7258: Shoplifting005_x264_12: Person 1 0
Processing 2490 of 7258: Shoplifting005_x264_13: Person 1 0
Processing 2491 of 7258: Shoplifting005_x264_14: Person 1 0
Processing 2492 of 7258: Shoplifting005_x264_14: Person 2 0
Processing 2493 of 7258: Shoplifting005_x264_15: Person 1 0
Processing 2494 of 7258: Shoplifting005_x264_15: Person 2 0
Processing 2495 of 7258: Shoplifting005_x264_15: Person 3 0
Processing 2496 of 7258: Shoplifting005_x264_16: Person 1 0
Processing 2497 of 7258: Shoplifting005_x264_16: Person 2 0
Processing 2498 of 7258: Shoplifting006_x264_0: Person 1 0
Processing 2499 of 7258: Shoplifting006_x264_0: Person 2 0
Processing 2500 of 7258: Shoplifting006_x264_1: Person 1 0
Processing 2501 of 7258: Shoplifting006_x264_1: Person 2 0
Processing 2502 of 7258: Shoplifting006_x264_2: Person 1 0
Processing 2503 of 7258: Shoplifting006_x264_2: Person 2 0
Processing 2504 of 7258: Shoplifting006_x264_3: Person 1 0
Processing 2505 of 7258: Shoplifting006_x264_4: Person 1 0
Processing 2506 of 7258: Shoplifting006_x264_5: Person 1 0
Processing 2507 of 7258: Shoplifting006_x264_6: Person 1 0
Processing 2508 of 7258: Shoplifting006_x264_8: Person 1 0
Processing 2509 of 7258: Shoplifting006_x264_9: Person 1 0
Processing 2510 of 7258: Shoplifting006_x264_9: Person 2 0
Processing 2511 of 7258: Shoplifting006_x264_15: Person 1 0
Processing 2512 of 7258: Shoplifting006_x264_15: Person 2 0
Processing 2513 of 7258: Shoplifting006_x264_16: Person 1 0
Processing 2514 of 7258: Shoplifting006_x264_16: Person 2 0
Processing 2515 of 7258: Shoplifting006_x264_16: Person 4 0
Processing 2516 of 7258: Shoplifting006_x264_16: Person 5 0
Processing 2517 of 7258: Shoplifting006_x264_16: Person 7 0
Processing 2518 of 7258: Shoplifting006_x264_17: Person 1 0
Processing 2519 of 7258: Shoplifting006_x264_17: Person 3 0
Processing 2520 of 7258: Shoplifting006_x264_17: Person 4 0
Processing 2521 of 7258: Shoplifting006_x264_17: Person 5 0
Processing 2522 of 7258: Shoplifting006_x264_18: Person 1 0
Processing 2523 of 7258: Shoplifting006_x264_18: Person 2 0
Processing 2524 of 7258: Shoplifting006_x264_19: Person 1 0
Processing 2525 of 7258: Shoplifting006_x264_19: Person 2 0
Processing 2526 of 7258: Shoplifting006_x264_19: Person 4 0
Processing 2527 of 7258: Shoplifting006_x264_19: Person 5 0
Processing 2528 of 7258: Shoplifting006_x264_19: Person 6 0
Processing 2529 of 7258: Shoplifting006_x264_20: Person 1 0
Processing 2530 of 7258: Shoplifting006_x264_20: Person 2 0
Processing 2531 of 7258: Shoplifting006_x264_20: Person 4 0
Processing 2532 of 7258: Shoplifting006_x264_21: Person 1 0
Processing 2533 of 7258: Shoplifting006_x264_21: Person 2 0
Processing 2534 of 7258: Shoplifting006_x264_22: Person 1 0
Processing 2535 of 7258: Shoplifting006_x264_22: Person 2 0
Processing 2536 of 7258: Shoplifting006_x264_22: Person 3 0
Processing 2537 of 7258: Shoplifting006_x264_22: Person 4 0
Processing 2538 of 7258: Shoplifting006_x264_22: Person 5 0
Processing 2539 of 7258: Shoplifting006_x264_23: Person 1 0
Processing 2540 of 7258: Shoplifting006_x264_23: Person 2 0
Processing 2541 of 7258: Shoplifting006_x264_23: Person 3 0
Processing 2542 of 7258: Shoplifting006_x264_23: Person 4 0
Processing 2543 of 7258: Shoplifting006_x264_23: Person 5 0
Processing 2544 of 7258: Shoplifting006_x264_23: Person 6 0
Processing 2545 of 7258: Shoplifting006_x264_24: Person 1 0
Processing 2546 of 7258: Shoplifting006_x264_24: Person 2 0
Processing 2547 of 7258: Shoplifting006_x264_25: Person 1 0
Processing 2548 of 7258: Shoplifting006_x264_25: Person 2 0
Processing 2549 of 7258: Shoplifting007_x264_0: Person 1 0
Processing 2550 of 7258: Shoplifting007_x264_0: Person 3 0
Processing 2551 of 7258: Shoplifting007_x264_1: Person 1 0
Processing 2552 of 7258: Shoplifting007_x264_1: Person 2 0
Processing 2553 of 7258: Shoplifting007_x264_2: Person 1 0
Processing 2554 of 7258: Shoplifting007_x264_2: Person 2 0
Processing 2555 of 7258: Shoplifting007_x264_2: Person 3 0
Processing 2556 of 7258: Shoplifting007_x264_3: Person 1 0
Processing 2557 of 7258: Shoplifting007_x264_3: Person 2 0
Processing 2558 of 7258: Shoplifting007_x264_3: Person 3 0
Processing 2559 of 7258: Shoplifting007_x264_11: Person 1 0
Processing 2560 of 7258: Shoplifting007_x264_11: Person 2 0
Processing 2561 of 7258: Shoplifting007_x264_13: Person 1 0
Processing 2562 of 7258: Shoplifting007_x264_20: Person 1 0
Processing 2563 of 7258: Shoplifting007_x264_20: Person 2 0
Processing 2564 of 7258: Shoplifting007_x264_20: Person 3 0
Processing 2565 of 7258: Shoplifting007_x264_21: Person 1 0
Processing 2566 of 7258: Shoplifting007_x264_21: Person 2 0
Processing 2567 of 7258: Shoplifting007_x264_22: Person 1 0
Processing 2568 of 7258: Shoplifting007_x264_23: Person 1 0
Processing 2569 of 7258: Shoplifting007_x264_23: Person 2 0
Processing 2570 of 7258: Shoplifting007_x264_23: Person 3 0
Processing 2571 of 7258: Shoplifting007_x264_24: Person 1 0
Processing 2572 of 7258: Shoplifting007_x264_24: Person 2 0
Processing 2573 of 7258: Shoplifting007_x264_24: Person 4 0
Processing 2574 of 7258: Shoplifting007_x264_24: Person 5 0
Processing 2575 of 7258: Shoplifting007_x264_25: Person 1 0
Processing 2576 of 7258: Shoplifting007_x264_25: Person 2 0
Processing 2577 of 7258: Shoplifting007_x264_25: Person 4 0
Processing 2578 of 7258: Shoplifting007_x264_25: Person 5 0
Processing 2579 of 7258: Shoplifting007_x264_26: Person 1 0
Processing 2580 of 7258: Shoplifting007_x264_26: Person 2 0
Processing 2581 of 7258: Shoplifting007_x264_26: Person 3 0
Processing 2582 of 7258: Shoplifting007_x264_26: Person 4 0
Processing 2583 of 7258: Shoplifting007_x264_27: Person 1 0
Processing 2584 of 7258: Shoplifting007_x264_27: Person 2 0
Processing 2585 of 7258: Shoplifting007_x264_27: Person 4 0
Processing 2586 of 7258: Shoplifting007_x264_27: Person 5 0
Processing 2587 of 7258: Shoplifting007_x264_28: Person 1 0
Processing 2588 of 7258: Shoplifting007_x264_28: Person 2 0
Processing 2589 of 7258: Shoplifting007_x264_28: Person 3 0
Processing 2590 of 7258: Shoplifting007_x264_29: Person 1 0
Processing 2591 of 7258: Shoplifting007_x264_29: Person 2 0
Processing 2592 of 7258: Shoplifting007_x264_29: Person 4 0
Processing 2593 of 7258: Shoplifting007_x264_30: Person 1 0
Processing 2594 of 7258: Shoplifting007_x264_30: Person 3 0
Processing 2595 of 7258: Shoplifting007_x264_30: Person 4 0

In [ ]:
def feature_vector_from_row_augmented(row):
  person_path = f"{yolo_path}/{row['Parent Video']}/{row['Clip']}/persons/person_{row['ID']}/keypoints_{row['Index']}.json"
  good_frames = row["Has Required"]
  with open(person_path) as f:
    vector = get_feature_vector(f, good_frames, padding="after")
  return vector

def get_good_frames_augmented(row):
  print(f"processing {row['Clip']}; person id: {row['ID']}; keypoint index: {row['Index']}")
  person_path = f"{yolo_path}/{row['Parent Video']}/{row['Clip']}/persons/person_{row['ID']}/keypoints_{row['Index']}.json"
  with open(person_path) as f:
    person = json.load(f)
  add_missing(person)
  required = []
  for frame in person:
    keypoints = person[frame][0]["keypoints"]
    # if has_required(keypoints):
    if has_neck(keypoints):
      required.append(frame[frame.find('_')+1:])
  return required

augmented_df = pd.read_csv(f"{output_path}/augmented_ids.csv")
augmented_df["Has Required"] = augmented_df.apply(get_good_frames_augmented, axis=1)
counts = augmented_df["Has Required"].map(len)
augmented_df = augmented_df[counts > 0]

feature_df = pd.DataFrame()
feature_df["clip"] = augmented_df["Clip"]
feature_df["parent"] = augmented_df["Parent Video"]
feature_df["id"] = augmented_df["ID"]
feature_df["index"] = augmented_df["Index"]
feature_df["features"] = augmented_df.apply(feature_vector_from_row_augmented, axis=1)
feature_df["target"] = augmented_df["Label"]
print(len(feature_df), feature_df["target"].value_counts())
feature_df.to_csv(f"{output_path}/augmented_features_eyes.csv", index=False)
feature_df.head()

Streaming output truncated to the last 5000 lines.
processing Shoplifting003_x264_82; person id: 2; keypoint index: 0
processing Shoplifting003_x264_83; person id: 1; keypoint index: 0
processing Shoplifting003_x264_83; person id: 2; keypoint index: 0
processing Shoplifting003_x264_84; person id: 1; keypoint index: 0
processing Shoplifting003_x264_86; person id: 1; keypoint index: 0
processing Shoplifting003_x264_86; person id: 2; keypoint index: 0
processing Shoplifting003_x264_87; person id: 1; keypoint index: 0
processing Shoplifting003_x264_87; person id: 2; keypoint index: 0
processing Shoplifting003_x264_87; person id: 3; keypoint index: 0
processing Shoplifting003_x264_88; person id: 1; keypoint index: 0
processing Shoplifting003_x264_89; person id: 1; keypoint index: 0
processing Shoplifting004_x264_0; person id: 1; keypoint index: 0
processing Shoplifting004_x264_0; person id: 2; keypoint index: 0
processing Shoplifting004_x264_0; person id: 3; keypoint index: 0
processing Shoplifting004_x264_1; person id: 1; keypoint index: 0
processing Shoplifting004_x264_1; person id: 2; keypoint index: 0
processing Shoplifting004_x264_2; person id: 1; keypoint index: 0
processing Shoplifting004_x264_2; person id: 2; keypoint index: 0
processing Shoplifting004_x264_2; person id: 3; keypoint index: 0
processing Shoplifting004_x264_3; person id: 1; keypoint index: 0
processing Shoplifting004_x264_3; person id: 2; keypoint index: 0
processing Shoplifting004_x264_4; person id: 1; keypoint index: 0
processing Shoplifting004_x264_4; person id: 2; keypoint index: 0
processing Shoplifting004_x264_4; person id: 3; keypoint index: 0
processing Shoplifting004_x264_4; person id: 4; keypoint index: 0
processing Shoplifting004_x264_5; person id: 1; keypoint index: 0
processing Shoplifting004_x264_5; person id: 2; keypoint index: 0
processing Shoplifting004_x264_5; person id: 4; keypoint index: 0
processing Shoplifting004_x264_6; person id: 1; keypoint index: 0
processing Shoplifting004_x264_6; person id: 2; keypoint index: 0
processing Shoplifting004_x264_6; person id: 3; keypoint index: 0
processing Shoplifting004_x264_6; person id: 4; keypoint index: 0
processing Shoplifting004_x264_7; person id: 1; keypoint index: 0
processing Shoplifting004_x264_7; person id: 3; keypoint index: 0
processing Shoplifting004_x264_8; person id: 1; keypoint index: 0
processing Shoplifting004_x264_8; person id: 2; keypoint index: 0
processing Shoplifting004_x264_8; person id: 3; keypoint index: 0
processing Shoplifting004_x264_8; person id: 4; keypoint index: 0
processing Shoplifting004_x264_9; person id: 1; keypoint index: 0
processing Shoplifting004_x264_9; person id: 3; keypoint index: 0
processing Shoplifting004_x264_9; person id: 4; keypoint index: 0
processing Shoplifting004_x264_9; person id: 5; keypoint index: 0
processing Shoplifting004_x264_9; person id: 6; keypoint index: 0
processing Shoplifting004_x264_9; person id: 7; keypoint index: 0
processing Shoplifting004_x264_10; person id: 1; keypoint index: 0
processing Shoplifting004_x264_10; person id: 2; keypoint index: 0
processing Shoplifting004_x264_10; person id: 3; keypoint index: 0
processing Shoplifting004_x264_11; person id: 1; keypoint index: 0
processing Shoplifting004_x264_11; person id: 2; keypoint index: 0
processing Shoplifting004_x264_11; person id: 3; keypoint index: 0
processing Shoplifting004_x264_11; person id: 4; keypoint index: 0
processing Shoplifting004_x264_11; person id: 6; keypoint index: 0
processing Shoplifting004_x264_12; person id: 1; keypoint index: 0
processing Shoplifting004_x264_12; person id: 2; keypoint index: 0
processing Shoplifting004_x264_12; person id: 3; keypoint index: 0
processing Shoplifting004_x264_13; person id: 1; keypoint index: 0
processing Shoplifting004_x264_13; person id: 2; keypoint index: 0
processing Shoplifting004_x264_13; person id: 5; keypoint index: 0
processing Shoplifting004_x264_14; person id: 1; keypoint index: 0
processing Shoplifting004_x264_14; person id: 3; keypoint index: 0
processing Shoplifting004_x264_14; person id: 5; keypoint index: 0
processing Shoplifting004_x264_14; person id: 7; keypoint index: 0
processing Shoplifting004_x264_15; person id: 1; keypoint index: 0
processing Shoplifting004_x264_15; person id: 2; keypoint index: 0
processing Shoplifting004_x264_15; person id: 3; keypoint index: 0
processing Shoplifting004_x264_16; person id: 1; keypoint index: 0
processing Shoplifting004_x264_16; person id: 2; keypoint index: 0
processing Shoplifting004_x264_16; person id: 3; keypoint index: 0
processing Shoplifting004_x264_16; person id: 6; keypoint index: 0
processing Shoplifting004_x264_17; person id: 1; keypoint index: 0
processing Shoplifting004_x264_17; person id: 2; keypoint index: 0
processing Shoplifting004_x264_17; person id: 3; keypoint index: 0
processing Shoplifting004_x264_17; person id: 4; keypoint index: 0
processing Shoplifting004_x264_17; person id: 6; keypoint index: 0
processing Shoplifting004_x264_18; person id: 1; keypoint index: 0
processing Shoplifting004_x264_18; person id: 2; keypoint index: 0
processing Shoplifting004_x264_18; person id: 3; keypoint index: 0
processing Shoplifting004_x264_18; person id: 4; keypoint index: 0
processing Shoplifting004_x264_19; person id: 1; keypoint index: 0
processing Shoplifting004_x264_19; person id: 2; keypoint index: 0
processing Shoplifting004_x264_19; person id: 3; keypoint index: 0
processing Shoplifting004_x264_19; person id: 4; keypoint index: 0
processing Shoplifting004_x264_20; person id: 1; keypoint index: 0
processing Shoplifting004_x264_20; person id: 2; keypoint index: 0
processing Shoplifting004_x264_20; person id: 3; keypoint index: 0
processing Shoplifting004_x264_20; person id: 4; keypoint index: 0
processing Shoplifting004_x264_21; person id: 1; keypoint index: 0
processing Shoplifting004_x264_21; person id: 2; keypoint index: 0
processing Shoplifting004_x264_21; person id: 3; keypoint index: 0
processing Shoplifting004_x264_21; person id: 4; keypoint index: 0
processing Shoplifting004_x264_22; person id: 1; keypoint index: 0
processing Shoplifting004_x264_22; person id: 2; keypoint index: 0
processing Shoplifting004_x264_22; person id: 3; keypoint index: 0
processing Shoplifting004_x264_22; person id: 4; keypoint index: 0
processing Shoplifting004_x264_23; person id: 1; keypoint index: 0
processing Shoplifting004_x264_23; person id: 2; keypoint index: 0
processing Shoplifting004_x264_23; person id: 3; keypoint index: 0
processing Shoplifting004_x264_23; person id: 4; keypoint index: 0
processing Shoplifting004_x264_23; person id: 5; keypoint index: 0
processing Shoplifting004_x264_24; person id: 1; keypoint index: 0
processing Shoplifting004_x264_24; person id: 2; keypoint index: 0
processing Shoplifting004_x264_24; person id: 3; keypoint index: 0
processing Shoplifting004_x264_24; person id: 4; keypoint index: 0
processing Shoplifting004_x264_25; person id: 1; keypoint index: 0
processing Shoplifting004_x264_25; person id: 2; keypoint index: 0
processing Shoplifting004_x264_25; person id: 3; keypoint index: 0
processing Shoplifting004_x264_25; person id: 5; keypoint index: 0
processing Shoplifting004_x264_26; person id: 1; keypoint index: 0
processing Shoplifting004_x264_26; person id: 2; keypoint index: 0
processing Shoplifting004_x264_26; person id: 3; keypoint index: 0
processing Shoplifting004_x264_26; person id: 4; keypoint index: 0
processing Shoplifting004_x264_26; person id: 6; keypoint index: 0
processing Shoplifting004_x264_26; person id: 7; keypoint index: 0
processing Shoplifting004_x264_27; person id: 1; keypoint index: 0
processing Shoplifting004_x264_27; person id: 2; keypoint index: 0
processing Shoplifting004_x264_27; person id: 3; keypoint index: 0
processing Shoplifting004_x264_27; person id: 6; keypoint index: 0
processing Shoplifting004_x264_27; person id: 7; keypoint index: 0
processing Shoplifting004_x264_27; person id: 10; keypoint index: 0
processing Shoplifting004_x264_28; person id: 1; keypoint index: 0
processing Shoplifting004_x264_28; person id: 2; keypoint index: 0
processing Shoplifting004_x264_28; person id: 3; keypoint index: 0
processing Shoplifting004_x264_28; person id: 4; keypoint index: 0
processing Shoplifting004_x264_28; person id: 6; keypoint index: 0
processing Shoplifting004_x264_29; person id: 1; keypoint index: 0
processing Shoplifting004_x264_29; person id: 2; keypoint index: 0
processing Shoplifting004_x264_29; person id: 3; keypoint index: 0
processing Shoplifting004_x264_29; person id: 8; keypoint index: 0
processing Shoplifting004_x264_29; person id: 9; keypoint index: 0
processing Shoplifting004_x264_30; person id: 1; keypoint index: 0
processing Shoplifting004_x264_30; person id: 2; keypoint index: 0
processing Shoplifting004_x264_30; person id: 3; keypoint index: 0
processing Shoplifting004_x264_30; person id: 4; keypoint index: 0
processing Shoplifting004_x264_30; person id: 5; keypoint index: 0
processing Shoplifting004_x264_31; person id: 1; keypoint index: 0
processing Shoplifting004_x264_31; person id: 2; keypoint index: 0
processing Shoplifting004_x264_31; person id: 3; keypoint index: 0
processing Shoplifting004_x264_31; person id: 4; keypoint index: 0
processing Shoplifting004_x264_32; person id: 1; keypoint index: 0
processing Shoplifting004_x264_32; person id: 2; keypoint index: 0
processing Shoplifting004_x264_32; person id: 3; keypoint index: 0
processing Shoplifting004_x264_32; person id: 4; keypoint index: 0
processing Shoplifting004_x264_32; person id: 6; keypoint index: 0
processing Shoplifting004_x264_33; person id: 1; keypoint index: 0
processing Shoplifting004_x264_33; person id: 2; keypoint index: 0
processing Shoplifting004_x264_33; person id: 3; keypoint index: 0
processing Shoplifting004_x264_33; person id: 4; keypoint index: 0
processing Shoplifting004_x264_34; person id: 1; keypoint index: 0
processing Shoplifting004_x264_34; person id: 2; keypoint index: 0
processing Shoplifting004_x264_34; person id: 3; keypoint index: 0
processing Shoplifting004_x264_34; person id: 4; keypoint index: 0
processing Shoplifting004_x264_35; person id: 1; keypoint index: 0
processing Shoplifting004_x264_35; person id: 2; keypoint index: 0
processing Shoplifting004_x264_35; person id: 3; keypoint index: 0
processing Shoplifting004_x264_35; person id: 4; keypoint index: 0
processing Shoplifting004_x264_35; person id: 5; keypoint index: 0
processing Shoplifting004_x264_36; person id: 1; keypoint index: 0
processing Shoplifting004_x264_36; person id: 2; keypoint index: 0
processing Shoplifting004_x264_36; person id: 3; keypoint index: 0
processing Shoplifting004_x264_36; person id: 4; keypoint index: 0
processing Shoplifting004_x264_37; person id: 1; keypoint index: 0
processing Shoplifting004_x264_37; person id: 2; keypoint index: 0
processing Shoplifting004_x264_37; person id: 3; keypoint index: 0
processing Shoplifting004_x264_37; person id: 4; keypoint index: 0
processing Shoplifting004_x264_37; person id: 5; keypoint index: 0
processing Shoplifting004_x264_42; person id: 1; keypoint index: 0
processing Shoplifting004_x264_42; person id: 2; keypoint index: 0
processing Shoplifting004_x264_43; person id: 1; keypoint index: 0
processing Shoplifting004_x264_43; person id: 2; keypoint index: 0
processing Shoplifting004_x264_44; person id: 1; keypoint index: 0
processing Shoplifting004_x264_44; person id: 2; keypoint index: 0
processing Shoplifting004_x264_44; person id: 4; keypoint index: 0
processing Shoplifting004_x264_45; person id: 1; keypoint index: 0
processing Shoplifting004_x264_45; person id: 2; keypoint index: 0
processing Shoplifting004_x264_46; person id: 1; keypoint index: 0
processing Shoplifting004_x264_46; person id: 2; keypoint index: 0
processing Shoplifting004_x264_47; person id: 1; keypoint index: 0
processing Shoplifting004_x264_47; person id: 2; keypoint index: 0
processing Shoplifting004_x264_47; person id: 3; keypoint index: 0
processing Shoplifting004_x264_47; person id: 4; keypoint index: 0
processing Shoplifting004_x264_48; person id: 1; keypoint index: 0
processing Shoplifting004_x264_48; person id: 2; keypoint index: 0
processing Shoplifting004_x264_48; person id: 3; keypoint index: 0
processing Shoplifting004_x264_48; person id: 4; keypoint index: 0
processing Shoplifting004_x264_49; person id: 1; keypoint index: 0
processing Shoplifting004_x264_49; person id: 2; keypoint index: 0
processing Shoplifting004_x264_49; person id: 4; keypoint index: 0
processing Shoplifting004_x264_49; person id: 7; keypoint index: 0
processing Shoplifting004_x264_50; person id: 1; keypoint index: 0
processing Shoplifting004_x264_50; person id: 2; keypoint index: 0
processing Shoplifting004_x264_50; person id: 3; keypoint index: 0
processing Shoplifting004_x264_50; person id: 4; keypoint index: 0
processing Shoplifting004_x264_51; person id: 1; keypoint index: 0
processing Shoplifting004_x264_51; person id: 2; keypoint index: 0
processing Shoplifting004_x264_51; person id: 3; keypoint index: 0
processing Shoplifting004_x264_52; person id: 1; keypoint index: 0
processing Shoplifting004_x264_52; person id: 2; keypoint index: 0
processing Shoplifting004_x264_52; person id: 4; keypoint index: 0
processing Shoplifting004_x264_53; person id: 1; keypoint index: 0
processing Shoplifting004_x264_53; person id: 2; keypoint index: 0
processing Shoplifting004_x264_53; person id: 5; keypoint index: 0
processing Shoplifting004_x264_54; person id: 1; keypoint index: 0
processing Shoplifting004_x264_54; person id: 2; keypoint index: 0
processing Shoplifting004_x264_54; person id: 4; keypoint index: 0
processing Shoplifting004_x264_54; person id: 5; keypoint index: 0
processing Shoplifting004_x264_55; person id: 1; keypoint index: 0
processing Shoplifting004_x264_55; person id: 2; keypoint index: 0
processing Shoplifting004_x264_55; person id: 3; keypoint index: 0
processing Shoplifting004_x264_55; person id: 5; keypoint index: 0
processing Shoplifting005_x264_0; person id: 1; keypoint index: 0
processing Shoplifting005_x264_1; person id: 1; keypoint index: 0
processing Shoplifting005_x264_1; person id: 2; keypoint index: 0
processing Shoplifting005_x264_1; person id: 3; keypoint index: 0
processing Shoplifting005_x264_2; person id: 1; keypoint index: 0
processing Shoplifting005_x264_2; person id: 2; keypoint index: 0
processing Shoplifting005_x264_2; person id: 3; keypoint index: 0
processing Shoplifting005_x264_3; person id: 1; keypoint index: 0
processing Shoplifting005_x264_3; person id: 2; keypoint index: 0
processing Shoplifting005_x264_3; person id: 3; keypoint index: 0
processing Shoplifting005_x264_4; person id: 1; keypoint index: 0
processing Shoplifting005_x264_5; person id: 1; keypoint index: 0
processing Shoplifting005_x264_5; person id: 2; keypoint index: 0
processing Shoplifting005_x264_8; person id: 1; keypoint index: 0
processing Shoplifting005_x264_9; person id: 1; keypoint index: 0
processing Shoplifting005_x264_10; person id: 1; keypoint index: 0
processing Shoplifting005_x264_11; person id: 1; keypoint index: 0
processing Shoplifting005_x264_12; person id: 1; keypoint index: 0
processing Shoplifting005_x264_13; person id: 1; keypoint index: 0
processing Shoplifting005_x264_14; person id: 1; keypoint index: 0
processing Shoplifting005_x264_14; person id: 2; keypoint index: 0
processing Shoplifting005_x264_15; person id: 1; keypoint index: 0
processing Shoplifting005_x264_15; person id: 2; keypoint index: 0
processing Shoplifting005_x264_15; person id: 3; keypoint index: 0
processing Shoplifting005_x264_16; person id: 1; keypoint index: 0
processing Shoplifting005_x264_16; person id: 2; keypoint index: 0
processing Shoplifting006_x264_0; person id: 1; keypoint index: 0
processing Shoplifting006_x264_0; person id: 2; keypoint index: 0
processing Shoplifting006_x264_1; person id: 1; keypoint index: 0
processing Shoplifting006_x264_1; person id: 2; keypoint index: 0
processing Shoplifting006_x264_2; person id: 1; keypoint index: 0
processing Shoplifting006_x264_2; person id: 2; keypoint index: 0
processing Shoplifting006_x264_3; person id: 1; keypoint index: 0
processing Shoplifting006_x264_4; person id: 1; keypoint index: 0
processing Shoplifting006_x264_5; person id: 1; keypoint index: 0
processing Shoplifting006_x264_6; person id: 1; keypoint index: 0
processing Shoplifting006_x264_8; person id: 1; keypoint index: 0
processing Shoplifting006_x264_9; person id: 1; keypoint index: 0
processing Shoplifting006_x264_9; person id: 2; keypoint index: 0
processing Shoplifting006_x264_15; person id: 1; keypoint index: 0
processing Shoplifting006_x264_15; person id: 2; keypoint index: 0
processing Shoplifting006_x264_16; person id: 1; keypoint index: 0
processing Shoplifting006_x264_16; person id: 2; keypoint index: 0
processing Shoplifting006_x264_16; person id: 4; keypoint index: 0
processing Shoplifting006_x264_16; person id: 5; keypoint index: 0
processing Shoplifting006_x264_16; person id: 7; keypoint index: 0
processing Shoplifting006_x264_17; person id: 1; keypoint index: 0
processing Shoplifting006_x264_17; person id: 3; keypoint index: 0
processing Shoplifting006_x264_17; person id: 4; keypoint index: 0
processing Shoplifting006_x264_17; person id: 5; keypoint index: 0
processing Shoplifting006_x264_18; person id: 1; keypoint index: 0
processing Shoplifting006_x264_18; person id: 2; keypoint index: 0
processing Shoplifting006_x264_19; person id: 1; keypoint index: 0
processing Shoplifting006_x264_19; person id: 2; keypoint index: 0
processing Shoplifting006_x264_19; person id: 4; keypoint index: 0
processing Shoplifting006_x264_19; person id: 5; keypoint index: 0
processing Shoplifting006_x264_19; person id: 6; keypoint index: 0
processing Shoplifting006_x264_20; person id: 1; keypoint index: 0
processing Shoplifting006_x264_20; person id: 2; keypoint index: 0
processing Shoplifting006_x264_20; person id: 4; keypoint index: 0
processing Shoplifting006_x264_21; person id: 1; keypoint index: 0
processing Shoplifting006_x264_21; person id: 2; keypoint index: 0
processing Shoplifting006_x264_22; person id: 1; keypoint index: 0
processing Shoplifting006_x264_22; person id: 2; keypoint index: 0
processing Shoplifting006_x264_22; person id: 3; keypoint index: 0
processing Shoplifting006_x264_22; person id: 4; keypoint index: 0
processing Shoplifting006_x264_22; person id: 5; keypoint index: 0
processing Shoplifting006_x264_23; person id: 1; keypoint index: 0
processing Shoplifting006_x264_23; person id: 2; keypoint index: 0
processing Shoplifting006_x264_23; person id: 3; keypoint index: 0
processing Shoplifting006_x264_23; person id: 4; keypoint index: 0
processing Shoplifting006_x264_23; person id: 5; keypoint index: 0
processing Shoplifting006_x264_23; person id: 6; keypoint index: 0
processing Shoplifting006_x264_24; person id: 1; keypoint index: 0
processing Shoplifting006_x264_24; person id: 2; keypoint index: 0
processing Shoplifting006_x264_25; person id: 1; keypoint index: 0
processing Shoplifting006_x264_25; person id: 2; keypoint index: 0
processing Shoplifting007_x264_0; person id: 1; keypoint index: 0
processing Shoplifting007_x264_0; person id: 3; keypoint index: 0
processing Shoplifting007_x264_1; person id: 1; keypoint index: 0
processing Shoplifting007_x264_1; person id: 2; keypoint index: 0
processing Shoplifting007_x264_2; person id: 1; keypoint index: 0
processing Shoplifting007_x264_2; person id: 2; keypoint index: 0
processing Shoplifting007_x264_2; person id: 3; keypoint index: 0
processing Shoplifting007_x264_3; person id: 1; keypoint index: 0
processing Shoplifting007_x264_3; person id: 2; keypoint index: 0
processing Shoplifting007_x264_3; person id: 3; keypoint index: 0
processing Shoplifting007_x264_11; person id: 1; keypoint index: 0
processing Shoplifting007_x264_11; person id: 2; keypoint index: 0

,clip,parent,id,index,features,target
0,Shoplifting001_x264_10,Shoplifting001_x264.mp4,1,0,"[0.0, 0.0, -3.6674314484295922, -3.86284365242...",1.0
1,Shoplifting001_x264_10,Shoplifting001_x264.mp4,1,1,"[0.0, 0.0, -3.6674313386379156, -3.86284353678...",1.0
2,Shoplifting001_x264_10,Shoplifting001_x264.mp4,1,2,"[0.0, 0.0, -4.450594156446924, -4.687735715992...",1.0
3,Shoplifting001_x264_10,Shoplifting001_x264.mp4,1,3,"[0.0, 0.0, -4.353060628912291, -4.585005297432...",1.0
4,Shoplifting001_x264_10,Shoplifting001_x264.mp4,1,4,"[0.0, 0.0, -3.0521017632907252, -3.21472727947...",1.0

In [ ]:
df = pd.read_csv(f"{output_path}/augmented_features_eyes.csv")
df["features"] = df["features"].map(json.loads)
print(df["target"].value_counts())
print(len(df.iloc[0]["features"]))
df.head()

target
0.0    5120
1.0    2009
Name: count, dtype: int64
7178

,clip,parent,id,index,features,target
0,Shoplifting001_x264_10,Shoplifting001_x264.mp4,1,0,"[0.0, 0.0, -3.6674314484295922, -3.86284365242...",1.0
1,Shoplifting001_x264_10,Shoplifting001_x264.mp4,1,1,"[0.0, 0.0, -3.6674313386379156, -3.86284353678...",1.0
2,Shoplifting001_x264_10,Shoplifting001_x264.mp4,1,2,"[0.0, 0.0, -4.450594156446924, -4.687735715992...",1.0
3,Shoplifting001_x264_10,Shoplifting001_x264.mp4,1,3,"[0.0, 0.0, -4.353060628912291, -4.585005297432...",1.0
4,Shoplifting001_x264_10,Shoplifting001_x264.mp4,1,4,"[0.0, 0.0, -3.0521017632907252, -3.21472727947...",1.0

In [ ]:
# update neck keypoints

#Testing

In [ ]:
ids_df = pd.read_csv(f"{output_path}/ids.csv")
print("Original IDs", len(ids_df), ids_df["Label"].value_counts())
feature_df = pd.read_csv(f"{output_path}/features.csv")
print("Original features", feature_df["target"].value_counts())
idfs_df = pd.read_csv(f"{output_path}/ids_eyes.csv")
print("IDs with eyes", len(ids_df), ids_df["Label"].value_counts())
feature_df = pd.read_csv(f"{output_path}/features_eyes.csv")
print("Features with eyes", feature_df["target"].value_counts())
ids_df = pd.read_csv(f"{output_path}/augmented_ids.csv")
print("Augmented IDs with eyes", len(ids_df), ids_df["Label"].value_counts())
feature_df = pd.read_csv(f"{output_path}/augmented_features_eyes.csv")
print("Augmented features with eyes", feature_df["target"].value_counts())

Original IDs 5558 Label
0.0    5218
1.0     340
Name: count, dtype: int64
IDs with eyes 5558 Label
0.0    5218
1.0     340
Name: count, dtype: int64
Augmented IDs with eyes 6403 Label
0.0    5218
1.0    1185
Name: count, dtype: int64
Augmented features with eyes target
0.0    1103
1.0     492
Name: count, dtype: int64
Features with eyes target
0.0    2845
1.0     211
Name: count, dtype: int64
Original features target
0.0    2845
1.0     211
Name: count, dtype: int64

In [ ]:
features = ["features.csv", "features_eyes.csv", "augmented_features.csv", "augmented_features_eyes.csv"]
for feature in features:
  print(feature)
  df = pd.read_csv(f"{output_path}/{feature}")
  print(len(df), df["target"].value_counts())

features.csv
2246 target
0.0    2064
1.0     182
Name: count, dtype: int64
features_eyes.csv
1200 target
0.0    1103
1.0      97
Name: count, dtype: int64
augmented_features.csv
3073 target
0.0    2064
1.0    1009
Name: count, dtype: int64
augmented_features_eyes.csv
1634 target
0.0    1103
1.0     531
Name: count, dtype: int64